/**
 * Detail records for /plan task popups. Keyed by task `id` from
 * +page.svelte. Add an entry only when there's enough substance to
 * warrant the popup; the page falls back to "no detail entry yet"
 * when missing.
 */

export interface PlanDetail {
  summary?: string;
  steps?: string[];
  acceptance?: string[];
  refs?: string[];
  /**
   * Recording of the e2e suite that verifies this task's work, per
   * CLAUDE.md Rule 12. Path is relative to /static/, e.g.
   * `/api/volume?path=test-recordings/e2e/115/routes.webm`. The Gantt popup renders an inline
   * <video controls> when set. Multiple recordings: pass the manifest
   * path instead (`/api/volume?path=test-recordings/e2e/<task>/manifest.json`) and the popup
   * lists each spec.
   *
   * Generated by: `bun run record:task -- <id>`
   * which runs `scripts/harvest_e2e_videos.ts`.
   */
  video?: string;
  videos?: string[];
}

export const details: Record<number, PlanDetail> = {
  // ───── A. Components ─────

  9: {
    summary:
      'Make a per-primitive spec MD the source of truth and generate the ManifoldCAD ' +
      'builder code from it, instead of the current "edit builder.ts directly" flow. ' +
      'The /primitives Script popup already surfaces the builder function for each ' +
      'primitive (sliced out of builder.ts via Vite ?raw); next step is to replace ' +
      'that read-only code view with an editable MD + a "regenerate builder" button.',
    steps: [
      'One-shot seed: run each of the 18 builder functions through Claude to produce ' +
        'a draft spec MD (ops vocabulary: tube/cyl/mv/rot/subtract/add/for-loop-of-rings). ' +
        'Commit the 18 docs as docs/primitives/<id>.md.',
      'Hand-curate the seeds where Claude invented post-hoc justifications.',
      'Define the spec DSL: structured MD with ops blocks (or YAML front-matter + ' +
        'narrative). Keep it tiny — same vocabulary the builders already use.',
      'Write the code generator: spec MD → TypeScript builder function. Wire it into ' +
        'a "regenerate" pipeline (CLI for now, button in /primitives Script popup later).',
      'Switch /primitives Script popup to render the MD (editable) instead of the .ts; ' +
        'regenerate writes the .ts back through the generator.',
    ],
    acceptance: [
      '18 per-primitive spec docs committed under docs/primitives/',
      'Code generator round-trips all 18: spec → generated .ts matches handwritten ' +
        'output byte-for-byte (or compiles to identical geometry under a fuzz test)',
      '/primitives Script popup edits the MD, button regenerates the builder',
    ],
    refs: [
      'src/routes/primitives/+page.svelte (Script popup)',
      'src/lib/cad/builder.ts (18 builder functions)',
    ],
  },

  10: {
    summary:
      'Build a prompt-tuned Claude that turns natural-language primitive ' +
      'descriptions ("a tube with 8 evenly-spaced grooves around the OD, 0.05 in ' +
      'deep") into ManifoldCAD builder code in the shape of the functions already ' +
      'in src/lib/cad/builder.ts. Close cousin of task 9 — both want the ' +
      'human-readable side to drive code generation — but this entry skips the ' +
      'structured spec MD and goes free-text → code in one step. Useful for adding ' +
      'a "describe a new primitive" input next to the + button in /primitives.',
    steps: [
      'Curate a few-shot prompt: 4-6 (description → builder function) pairs sampled ' +
        'from existing builders. Include the helper vocabulary (cyl, tube, mv, rot, ' +
        'subtract, add) and the per-method shape (function name, p destructure, ' +
        'manifold-chain return).',
      'Pin the output to ManifoldCAD\'s API surface — system prompt enumerates the ' +
        'allowed operations + cube/cylinder/sphere primitives, forbids anything else.',
      'Wire a server endpoint /api/primitives/generate that accepts {description, ' +
        'name?, paramHints?} and returns {builderSrc, paramDefs}. Subject to the same ' +
        'rate-limit bucket as /api/identify.',
      'Hook the + button in /primitives: type a description → call endpoint → drop ' +
        'the new builder into a draft tab with the generated source + params. Save = ' +
        'append the function to builder.ts + the ComponentDef to library.ts.',
      'Safety: never eval the generated code in-browser. Treat it as text the user ' +
        'reviews and commits — same rule as task 9 + CLAUDE.md no-dynamic-eval.',
    ],
    acceptance: [
      'Generate clean builder code for ~5 fresh primitive descriptions (eg "ribbed ' +
        'sleeve", "hexagonal sub") that compile without manual edits',
      'Bad inputs (vague descriptions, unsupported geometry) return a helpful error ' +
        'message instead of malformed code',
      '/primitives + button shows the NL input field and the round-trip works ' +
        'end-to-end',
    ],
    refs: [
      'src/lib/cad/builder.ts (target shape — function bodies to emit)',
      'src/lib/cad/library.ts (target shape — ComponentDef to emit alongside)',
      'CLAUDE.md (no-dynamic-eval rule)',
    ],
  },

  // ───── I. 4-level hierarchy + composite generators ─────

  400: {
    summary:
      'Restructured /primitives into a 4-tab sidebar matching the formal hierarchy ' +
      '(Primitive / Composition / Component / Assembly) plus a 5th tab for KB browsing. ' +
      'Each tab opens entries as in-tab Threlte canvas tabs in the main bar; the cards ' +
      'grid is gone, navigation is sidebar-driven. Vertical tab rail on the left of the ' +
      'sidebar with rotated wedge-shaped buttons; primary content area gets the full ' +
      'remaining width. Camera/light defaults shared with /author via $lib/shared/scene-state.',
    refs: ['docs/RULES.md', 'src/routes/primitives/+page.svelte'],
  },

  401: {
    summary:
      'Variation generator pattern in src/lib/cad/library.ts. ComponentDef gains ' +
      'an optional `parent: string` field; deriveVariation(spec) builds a child ' +
      'ComponentDef that inherits the parent\'s param schema + builder geometry, only ' +
      'overriding `defaults` and (optionally) per-param ranges. buildPrimitiveManifold ' +
      'walks the parent chain to find a registered builder when the child has none. ' +
      'New variants need ~8 lines, no builder code.',
    acceptance: [
      '6 SC/LC/BC box+pin variants generated from a 6-entry VARIATION_SPECS table',
      'Each renders distinct geometry (different OD, length, thread density, taper)',
      'Sidebar shows parent threaded_box / threaded_pin as 📁 folders with the count pill',
    ],
    refs: ['docs/RULES.md §3', 'src/lib/cad/library.ts'],
  },

  402: {
    summary:
      'src/lib/cad/rules/tubing.ts — first formalized composite generator. ' +
      'TubingInputs (size, weight, grade, connection, length, tpi) → resolveTubing ' +
      '(KB lookup against casing-tubing-data with formula fallback) → TubingDerived ' +
      '(wall, pipe_id, connection_od, connection_length, thread_count, thread_taper, ' +
      'mut_opti) → buildTubingSpec → AuthoredComponent with body + top_box + bot_pin. ' +
      'Box-on-top / pin-on-bottom convention encoded.',
    acceptance: [
      'KB-anchored values lift wall/ID/coupling-OD/conn-length verbatim from KB rows',
      'Formula fallback gives reasonable values when no KB row matches',
      '4 standard tubing sizes (2-3/8, 2-7/8, 3-1/2, 4-1/2) generated through the rules',
    ],
    refs: ['docs/RULES.md §4', 'src/lib/cad/rules/tubing.ts'],
  },

  403: {
    summary:
      'Sister rules file for drill pipe + new identification KB. KB has 8 marking rows ' +
      'mapping (weight_class, grade) → (num_grooves, num_slots, groove_wide). New ' +
      'primitive drill_pipe_tool_joint renders these as parametric grooves + slots on ' +
      'the tong-area band. rules/drill_pipe.ts mirrors the tubing pipeline with ' +
      'DrillPipeInputs and KB-driven marking resolution.',
    acceptance: [
      'KB at static/kb/api/drill-pipe-identification.json with all 8 marking combinations',
      'Manifest entry in static/kb/index.json so the sidebar KB tab lists it automatically',
      'drill_pipe_tool_joint primitive registered in library.ts + builder.ts',
      'Both ends of a generated drill pipe joint carry the same identifying marks',
    ],
    refs: ['docs/RULES.md §8', 'src/lib/cad/rules/drill_pipe.ts', 'static/kb/api/drill-pipe-identification.json'],
  },

  404: {
    summary:
      'KbTableViewer.svelte gains an optional `rowAction` prop (icon + title + onAction). ' +
      'On the casing-tubing KB tab, every row now carries a ▶ button that invokes ' +
      'generateTubingComponent with the row\'s (size, weight, grade, connection) and ' +
      'opens the resulting joint as a composite tab in the main bar.',
    refs: ['src/lib/shared/KbTableViewer.svelte', 'src/routes/primitives/+page.svelte'],
  },

  405: {
    summary:
      'Three new primitives synthesized from the Halliburton catalogs in ~/Downloads:' +
      ' window_cutout (LatchRite pre-milled multilateral window), whipstock (deflector ' +
      'wedge), sliding_sleeve (generic ICV mandrel — body + N axial ports + seal bores). ' +
      'Plus drill_pipe_tool_joint with the parametric marking band. Each registered ' +
      'in library.ts with full param schemas; renders inline like any other primitive.',
    refs: [
      'src/lib/cad/builder.ts',
      'src/lib/cad/library.ts',
      '~/Downloads/556242167-Intelligent-Completions-Catalog.pdf',
      '~/Downloads/633400581-02-Multilateral-Technology-Catalog-pdf.pdf',
    ],
  },

  408: {
    summary:
      'Bottom-sub and ratch-latch builders use a separate Manifold WASM init lifecycle ' +
      'and nested AssemblyParams shapes that don\'t fit the flat ComponentDef record. ' +
      'Two clean paths: (a) add a buildUnifiedManifold(flatParams) to each tool that ' +
      'converts flat → nested + returns one manifold, then register them as builders; ' +
      '(b) introduce a `tool` tab kind that mounts the existing Scene component ' +
      'dynamically. (a) unifies the rendering path.',
    refs: ['src/lib/tools/bottom-sub/builder.ts', 'src/lib/tools/ratch-latch/builder.ts'],
  },

  409: {
    summary:
      'Auto-list every (size, weight, grade) row in the casing-tubing KB as its own ' +
      'composition entry under Compositions / Standard API tubing or casing. Sidebar ' +
      'becomes the catalog itself; clicking generates the composite via the rules. ' +
      'Reduces the hand-curated COMPONENTS_L3 list to just the catalog-inspired entries.',
    refs: ['src/lib/cad/rules/tubing.ts'],
  },

  410: {
    summary:
      'Multilateral catalog extractor — mirror of scripts/kb/build_casing_tubing_data.ts ' +
      'for the 633400581 PDF. Output at static/kb/api/multilateral-junctions.json ' +
      'covering pre-milled windows, latch couplings, whipstocks per TAML level. ' +
      'Auto-listed as a 3rd KB tab entry once the JSON exists.',
    refs: ['~/Downloads/633400581-02-Multilateral-Technology-Catalog-pdf.pdf'],
  },

  411: {
    summary:
      'Composition tabs are currently read-only (params baked into each part\'s spec). ' +
      'Editable mode: the Params popup on a tubing/drill-pipe composite shows the input ' +
      'fields (size, weight, grade, length, tpi); editing reruns the rules pipeline ' +
      'and rebuilds the spec → live geometry update. Carries through the KB-anchored / ' +
      'formula-derived flag so the user sees which dims are pinned.',
    refs: ['src/lib/cad/rules/tubing.ts', 'src/routes/primitives/+page.svelte'],
  },

  412: {
    summary:
      'thread_if / thread_fh / thread_nc currently each ship a hand-written builder. ' +
      'Convert to AuthoredComponent specs (body + drill_pipe_tool_joint with the right ' +
      'marking + flush-bore variant of threaded_pin). Drops three custom builders, ' +
      'tightens the convention from §2.',
    refs: ['docs/RULES.md §2 §9', 'src/lib/cad/builder.ts'],
  },

  // ───── B. Retrieval ─────

  26: {
    summary:
      'CLIP retrieval rolled out end-to-end (commits 9b67c29..81261c5). ' +
      '@xenova/transformers integrated with sharp + a Bun compat shim for ' +
      'Node↔Bun parity. Hybrid scoring: 0.75·cos + 0.15·sameCategory + ' +
      '0.10·(1 - ham/64). Migration script embedded all 1,772 cache records ' +
      'plus 700 synthetic samples.',
    acceptance: [
      'Build clean on both bun --bun and bun (Node 25)',
      '50 vitest tests pass',
      'cache.jsonl: 1,772 records each carry a 512-dim embedding',
      '/api/identify computes embedding + pHash in parallel (Promise.all)',
    ],
    refs: ['~/.claude/plans/clip-retrieval-and-synthetic-data.md'],
  },

  28: {
    summary:
      'CLIP collapses on default-param primitive renders — 12 of 18 primitives ' +
      'produce identical embeddings (cos = 1.000) because the silhouettes are ' +
      'too abstract for CLIP\'s natural-image training distribution. The ' +
      'CLAUDE.md TODO lists four options: re-render with shading + color, ' +
      'add edge-histogram fingerprint, fine-tune CLIP on the primitive set, ' +
      'or replace the 18-image test with real photo benchmarks.',
    refs: ['CLAUDE.md (Open TODOs)', '~/.claude/projects/.../memory/clip_silhouette_collapse.md'],
  },

  // ───── D. Wells ─────

  60: {
    summary:
      'Mirror SVTC\'s WSON shape into cadtrain so /api/wells/extract emits a ' +
      'document SVTC\'s drawing apps can absorb directly. Schema lives at ' +
      'src/lib/wells/schema.ts; the canonical reference is SVTC\'s ' +
      'src/lib/apps/wson/CLAUDE.md (lines 108-148). Single root object, not an array.',
    steps: [
      'Define TypeScript interfaces for WSON top-level: meta, oh[], ch[], cementing[], completions[], perforations[], strata[], profile[]',
      'Add a small zod (or hand-rolled) validator so extracted JSON can be sanity-checked before save',
      'Document the rules from SVTC\'s CLAUDE.md (e.g., tubing in completions[], not ch[])',
    ],
    acceptance: [
      'src/lib/wells/schema.ts exports WSON + section types',
      'A round-trip test parses + serialises a minimal valid WSON without loss',
    ],
    refs: ['~/Desktop/GitHub/SVTC/src/lib/apps/wson/CLAUDE.md'],
  },

  61: {
    summary:
      'Server endpoint that takes a well document (PDF or image + optional text) and ' +
      'returns a WSON object via Claude vision. PDFs go through type:document so ' +
      'Claude sees the text layer + vector elements directly — much cleaner than ' +
      'rasterising first. Output is validated against schema.ts before return.',
    refs: ['~/.claude/plans/clip-retrieval-and-synthetic-data.md (out-of-scope §)'],
  },

  62: {
    summary:
      '/wells route — upload a document, watch live extraction, edit, save. ' +
      'Mirrors the /reverse pattern (upload → identify → refine → save) but ' +
      'for documents instead of component images.',
  },

  // ───── F. Meta ─────

  100: {
    summary: 'This page. Built 2026-05-09, mirrors the Gantt pattern from sister-repo SVTC.',
    refs: ['~/Desktop/GitHub/SVTC/src/routes/plan/+page.svelte'],
  },

  // ───── F. Two-product split ─────

  110: {
    summary:
      'Extract the API/CLI dispatch pattern that\'s currently duplicated across ' +
      'src/lib/identify/backend.ts and src/lib/wells/backend.ts. Six small modules ' +
      'in src/lib/shared/: mime-ext, anthropic-client, cli-subprocess, cli-output-parse, ' +
      'temp-file, cli-args. Both existing backends refactored to call shared/. RAG and ' +
      'domain prompts stay in their backend files. ~150 LOC saved.',
    steps: [
      'Create src/lib/shared/mime-ext.ts — guessImageExt(mime)',
      'Create src/lib/shared/anthropic-client.ts — requireAnthropicKey() + createAnthropicClient()',
      'Create src/lib/shared/cli-subprocess.ts — spawnClaudeCli(args, cleanupPaths)',
      'Create src/lib/shared/cli-output-parse.ts — parseCliEnvelope(stdout, opts)',
      'Create src/lib/shared/temp-file.ts — withTempFile(prefix, ext, buffer, fn)',
      'Create src/lib/shared/cli-args.ts — buildClaudeCliArgs({ model, addDir, system, user })',
      'Refactor identify/backend.ts to use shared/',
      'Refactor wells/backend.ts to use shared/',
      'Verify: bun run build, bun test, manual /reverse + /wells smoke test',
    ],
    acceptance: [
      'bun run build clean',
      'bun test passes (50+ tests)',
      'Image upload at /reverse returns identification result',
      'PDF upload at /wells returns valid WSON',
      '~150 LOC removed from backend.ts files',
    ],
    refs: ['~/.claude/plans/silly-conjuring-deer.md'],
  },

  111: {
    summary:
      'Move all current user-facing routes under src/routes/archive/* so they remain ' +
      'a reference but are unambiguously "old work." API routes stay at /api/* (no URL ' +
      'change to avoid breaking archived pages). The src/lib/* tree stays put this PR — ' +
      'reorganizing lib paths is a separate ~40-file rename PR.',
    steps: [
      '(training)/components → archive/(training)/components',
      '(training)/reverse → archive/(training)/reverse',
      '(training)/training → archive/(training)/training',
      '(training)/tests → archive/(training)/tests (incl. tests/components, tests/wells)',
      '(build)/author → archive/(build)/author',
      '(build)/library → archive/(build)/library',
      'tools/bottom-sub → archive/tools/bottom-sub',
      'tools/ratch-latch → archive/tools/ratch-latch',
      'wells → archive/wells',
      'Update internal links in 6 page files (Tests, Author, Library back-/forward-links)',
    ],
    acceptance: [
      'Every archived URL loads in dev server',
      'Intra-archive nav works (Tests → Tests/Wells, Author → Library)',
      '/api/identify and /api/wells/extract still respond from archive pages',
      'Static assets (/training_data, /eval, /tests) still resolve',
    ],
    refs: ['~/.claude/plans/silly-conjuring-deer.md'],
  },

  112: {
    summary:
      'Replace the current 5-segment navbar (Training · Build · Tools · Wells · Meta) ' +
      'with a 4-segment layout: CAD | Wells | Archive | Meta. CAD and Wells initially ' +
      'point to empty stubs; Archive expands to all 9 archived routes; Meta stays.',
    refs: ['~/.claude/plans/silly-conjuring-deer.md'],
  },

  113: {
    summary:
      'Create src/routes/cad/+page.svelte and src/routes/wells/+page.svelte as ' +
      'placeholders explaining the new products are under construction. Rewrite ' +
      'src/routes/+page.svelte as a clean two-product landing. Optionally add ' +
      'src/routes/archive/+page.svelte as an index of legacy routes.',
    refs: ['~/.claude/plans/silly-conjuring-deer.md'],
  },

  114: {
    summary:
      'Rewrite the Routes table in CLAUDE.md to reflect CAD / Wells / Archive / Meta ' +
      'split. Add a Methodology (shared) section documenting: dual-backend dispatch ' +
      'pattern (API vs CLI), cold-classification baseline finding, cache-grows-with-use ' +
      'compounding loop, 5-layer validation hierarchy. Add lib/shared/ subsection with ' +
      'the 4 new modules. Document the cad/wells no-cross-import rule. Add Rule 11 ' +
      '(prompt for e2e tests after route/UI/backend changes, asking headless vs headed).',
    refs: ['~/.claude/plans/silly-conjuring-deer.md', 'CLAUDE.md'],
  },

  115: {
    summary:
      'Playwright e2e suite added (commit ~ after 55b1f43). 44 tests in 3 specs ' +
      'under tests/e2e/. Auto-spawns dev server on port 4445 to avoid colliding ' +
      'with manual `bun run dev` on 3333. Headless run completes in ~15s.',
    videos: [
      '/api/volume?path=test-recordings/e2e/115/routes.webm',
      '/api/volume?path=test-recordings/e2e/115/navbar.webm',
      '/api/volume?path=test-recordings/e2e/115/archive-links.webm',
    ],
    steps: [
      'bun add -d @playwright/test',
      'bunx playwright install chromium',
      'tests/e2e/routes.spec.ts — 16 active routes return 200, 8 removed top-level URLs return 404',
      'tests/e2e/navbar.spec.ts — 4 segments visible, 10 archive links listed, active highlighting works, click-through navigation',
      'tests/e2e/archive-links.spec.ts — no stale top-level links inside any archived page; intra-archive nav resolves',
      'playwright.config.ts — PWHEAD=1 toggles headed mode with slowMo 250',
    ],
    acceptance: [
      '`bun run test:e2e` passes 44/44 in ~15s',
      '`bun run test:e2e:headed` opens visible Chromium for debugging',
      'CLAUDE.md Rule 11 codifies when to prompt the user to run it',
      'Memory file feedback_test_after_route_changes.md persists rule across sessions',
    ],
    refs: ['playwright.config.ts', 'tests/e2e/'],
  },

  116: {
    summary:
      'Backend smoke tests added at tests/e2e/backend.spec.ts. Six tests across ' +
      '/api/wells/extract and /api/identify. Structural tests (4) verify request ' +
      'parsing — 400 on missing/wrong field, correct error messages — and run on ' +
      'every e2e invocation. Live tests (2) are gated behind CADTRAIN_E2E_LIVE=1 ' +
      'env var: with it, they upload a real well doc PNG and a primitive render ' +
      'and assert the full response shape from the actual Anthropic API. Without ' +
      'it, they auto-skip — keeps the default suite cheap and deterministic.',
    steps: [
      'tests/e2e/backend.spec.ts — 4 structural + 2 live tests',
      'liveTest = LIVE ? test : test.skip pattern for env-gated execution',
      'Fixtures: static/eval/wells/Ananas-13-*.png (104 KB), primitive renders fallback chain',
      'Mode banner test logs whether LIVE mode is on',
    ],
    acceptance: [
      '48 passed + 2 skipped (= 50 total) without CADTRAIN_E2E_LIVE',
      '50 passed with CADTRAIN_E2E_LIVE=1 (verified locally; not run in CI)',
      'Catches Phase 0 backend refactor regressions: form-field name drift, status code drift',
    ],
    refs: [
      'src/routes/api/wells/extract/+server.ts',
      'src/routes/api/identify/+server.ts',
      'tests/e2e/backend.spec.ts',
    ],
    videos: [
      '/api/volume?path=test-recordings/e2e/116/routes.webm',
      '/api/volume?path=test-recordings/e2e/116/navbar.webm',
      '/api/volume?path=test-recordings/e2e/116/archive-links.webm',
    ],
  },

  117: {
    summary:
      '.github/workflows/ci.yml extended with two jobs: build (bun install, bun test, ' +
      'bun run build) and e2e (needs build, installs Playwright chromium, runs ' +
      '`bun run test:e2e`). Live API tests gated by CADTRAIN_E2E_LIVE which is ' +
      "explicitly '0' in CI — Anthropic tokens are never burned by CI, only by local " +
      'opt-in. paths-ignore skips runs on **/*.md, .gitignore, static/eval/**, and ' +
      'static/tests/** so docs/data-only changes do not waste minutes. ' +
      'On failure the e2e job uploads tests/results/playwright-report/ and ' +
      'tests/results/playwright-output/ as artifacts (7-day retention) so a failed ' +
      'run on GitHub gives you the HTML report + WEBM videos to download.\n\n' +
      'Pre-existing failure: src/lib/authoring/compose.test.ts has an unrelated ' +
      "module-resolution error ('$lib/cad/builder' not found). Confirmed " +
      'pre-existing on main, unrelated to the restructure. Unit-test step is set to ' +
      'continue-on-error: true; revisit when authoring gets its own lib/ reorg.',
    steps: [
      '.github/workflows/ci.yml: build job (Bun install + bun test + bun run build)',
      '.github/workflows/ci.yml: e2e job needs build, installs Playwright, runs test:e2e',
      'paths-ignore: docs and static/eval, static/tests changes skip CI',
      'CADTRAIN_E2E_LIVE: 0 hard-coded — CI never burns Anthropic tokens',
      'Failure artifacts: playwright-report + playwright-videos uploaded for 7 days',
    ],
    acceptance: [
      'Pushing a branch with code changes triggers the build + e2e jobs',
      'A docs-only PR (only **/*.md changed) does NOT trigger CI',
      'A failed e2e run leaves a downloadable HTML report + WEBM videos as artifacts',
    ],
    refs: ['.github/workflows/ci.yml'],
    videos: [
      '/api/volume?path=test-recordings/e2e/117/routes.webm',
      '/api/volume?path=test-recordings/e2e/117/navbar.webm',
      '/api/volume?path=test-recordings/e2e/117/archive-links.webm',
    ],
  },

  118: {
    summary:
      'Rule 12 made operational. scripts/harvest_e2e_videos.ts wraps `bun run test:e2e`, ' +
      'then walks tests/results/playwright-output/ and copies the largest WEBM per spec ' +
      'into <volume>/test-recordings/e2e/<task-id>/<spec>.webm with a manifest.json. Classifier matches ' +
      'against KNOWN_SPECS = [routes, navbar, archive-links, backend] (longest match wins).\n\n' +
      'PlanDetail extended with video / videos fields. The Gantt popup renders inline ' +
      '<video controls> with a caption + a hint pointing at `bun run record:task`.',
    steps: [
      'scripts/harvest_e2e_videos.ts written; --task <id>, --no-run, --spec flags',
      'package.json: bun run record:task <id>',
      'PlanDetail interface gets video?: string and videos?: string[]',
      '/plan popup body renders <video> when present',
      'CSS adds .video-caption, .video-hint, video styling',
    ],
    acceptance: [
      '`bun run record:task -- 115` produces routes.webm, navbar.webm, archive-links.webm + manifest.json',
      'Opening task 115 in /plan shows 3 inline playable WEBMs',
      'No regressions: build clean, e2e 44/44',
    ],
    videos: [
      '/api/volume?path=test-recordings/e2e/115/routes.webm',
      '/api/volume?path=test-recordings/e2e/115/navbar.webm',
      '/api/volume?path=test-recordings/e2e/115/archive-links.webm',
    ],
  },

  119: {
    summary:
      'Home page reduced to an SVTC-style menu (no marketing copy, no cards): ' +
      'just .menu-header + a clean list of routes (CAD / Wells / Tests / Plan / Archive) ' +
      'with one-line hints.\n\n' +
      'Navbar restructured: dropped the segment+items pattern (and seg-label/sep CSS) ' +
      'in favour of a flat top-level link list. Tests promoted to a top-level entry pointing ' +
      'at /archive/tests so recordings + cache stats are one click away (was buried under ' +
      'the Archive collapse before).\n\n' +
      'Active-state matching switched from per-link prefix to longest-match-wins so visiting ' +
      '/archive/tests highlights Tests (not both Tests AND Archive). $derived.by computes the ' +
      'single winning href once and the loop just compares against it.',
    steps: [
      '+layout.svelte: navLinks array; activeHref derived via longest-prefix match',
      '+page.svelte: rewritten as .menu with .menu-header + 5 .menu-item entries',
      'navbar.spec.ts: rewritten to assert the 5 nav links + Tests promotion + home-menu parity',
      'routes.spec.ts: / no longer has <h1>; assertion targets .menu-header instead',
    ],
    acceptance: [
      'Home page shows only the menu — no hero text, no cards, no footer note',
      'Navbar shows: CAD / Wells / Tests / Plan / Archive (Tests links to /archive/tests)',
      'Visiting /archive/tests highlights Tests in the navbar, NOT Archive',
      'e2e suite green: 49/49 (2 LIVE-gated skipped)',
    ],
    refs: [
      'src/routes/+layout.svelte',
      'src/routes/+page.svelte',
      'tests/e2e/navbar.spec.ts',
    ],
    videos: [
      '/api/volume?path=test-recordings/e2e/119/routes.webm',
      '/api/volume?path=test-recordings/e2e/119/navbar.webm',
      '/api/volume?path=test-recordings/e2e/119/archive-links.webm',
    ],
  },

  120: {
    summary:
      'Two mobile usability fixes after the user reported the /archive/components ' +
      'page was unreadable on iPhone (4-column layout overlapping):\n\n' +
      '1) **Responsive breakpoint at 900px.** Every multi-column archive page now ' +
      'switches to flex-direction: column on phones/narrow tablets — sidebar / 3D ' +
      'viewport / svg+png / params stack vertically with min-height: 380px on the ' +
      '3D canvas so it has room to render.\n\n' +
      '2) **Collapsible side panels.** Each side panel (parameters, metadata, parts/ops, ' +
      'svg/png previews) gets a header toggle button. Click → panel collapses to a ' +
      'thin 36px sliver with vertical-text title. Choice persists in localStorage ' +
      '(`comp:showParams`, `author:showMeta`, etc) so the user\'s preference sticks ' +
      'across reloads. Default = open on desktop, closed on phones.',
    refs: [
      'src/routes/archive/components/+page.svelte',
      'src/routes/archive/author/+page.svelte (now src/routes/author/)',
      'src/routes/archive/reverse/+page.svelte',
      'src/routes/archive/tests/+page.svelte',
      'src/routes/archive/tools/bottom-sub/+page.svelte',
      'src/routes/archive/tools/ratch-latch/+page.svelte',
    ],
  },

  121: {
    summary:
      'Author + Library promoted from /archive/* to top-level (/author and /library). ' +
      'They\'re the active surface for working with generated 3D models — the library ' +
      'lists every authored component, the author renders one in 3D + lets you tweak ' +
      'parts, params, transforms, and CSG ops. They cross-reference each other (Library ' +
      'links each card to /author?id=...; Author has a "Browse library" link back).\n\n' +
      'Navbar restructured: Library + Author replace CAD as the primary CAD surface ' +
      '(CAD stub still reachable at /cad but not in navbar). Six top-level links now: ' +
      'Library / Author / Wells / Tests / Plan / Archive.\n\n' +
      'Archive index updated — the Authoring section is gone since those routes left ' +
      '/archive. e2e specs updated for new paths + nav count.',
    steps: [
      'git mv src/routes/archive/{author,library} → src/routes/{author,library}',
      'sed all internal /archive/{author,library} references → /{author,library}',
      'src/routes/+layout.svelte: navLinks adds Library + Author, drops CAD',
      'src/routes/+page.svelte: home menu mirrors new navbar',
      'tests/e2e/{routes,navbar,archive-links}.spec.ts: new paths + 6-link nav count',
    ],
    acceptance: [
      '/library returns 200 and lists 10+ authored components',
      '/author returns 200 with the editor (parts/ops sidebar + 3D viewport + meta panel)',
      'Navbar shows: Library | Author | Wells | Tests | Plan | Archive',
      'Library card click → /author?id=<id> renders that model in 3D',
      'e2e green',
    ],
    videos: [
      '/api/volume?path=test-recordings/e2e/121/routes.webm',
      '/api/volume?path=test-recordings/e2e/121/navbar.webm',
      '/api/volume?path=test-recordings/e2e/121/archive-links.webm',
    ],
  },

  122: {
    summary:
      'User reported: Opus-generated assemblies (8-12 parts each) crashed mobile ' +
      'Safari while bottom-sub (single dedicated builder) works fine even at high ' +
      'precision. Investigation: bottom-sub returns SEPARATE manifolds per piece ' +
      '(housing, slips, sleeve) and renders 3 independent meshes. Old compose.ts ' +
      'UNIONED all parts into one giant manifold — peak WASM heap during the union ' +
      "exceeded mobile Safari's ~1GB cap → tab killed.\n\n" +
      'Fix: refactor buildAuthored() to mirror bottom-sub. Each part is finalized ' +
      'independently (own centering + own cutaway-box subtract); ComponentScene ' +
      'now accepts AuthoredResult { parts: [...] } and renders one <T.Mesh> per ' +
      'part. CSG ops still fuse THEIR inputs (typically 2-3 inputs, fine for heap), ' +
      'and the op output replaces its inputs in the render set.\n\n' +
      'Restored 192-segment precision (was 64 in the previous quick fix). The ' +
      'CIRCULAR_SEGMENTS_COMPOSE infrastructure stays in place for future use but ' +
      'is no longer called.\n\n' +
      'Why CSG was the bottleneck: WASM is single-threaded, runs on the main JS ' +
      'thread, blocks the event loop. It does NOT run in parallel with rendering — ' +
      'the build phase is sequential, then the GPU renders the result. Memory ' +
      'peak during build phase = the constraint.',
    refs: [
      'src/lib/authoring/compose.ts',
      'src/lib/shared/ComponentScene.svelte',
    ],
  },

  123: {
    summary:
      'GLB-via-REST: move ALL ManifoldCAD work to the server (Node WASM) and let ' +
      'the client be a pure GLTFLoader. Mobile never spawns WASM, never holds CSG ' +
      'heap, never crashes — the constraint that drives F.122 just disappears.\n\n' +
      'Two flows, both backed by the same content-addressed GLB cache:\n\n' +
      '**1. Browse (/library) — saved-spec GLBs:**\n' +
      ' - On /api/author/save, the server runs buildAuthored() server-side, ' +
      'serializes to GLB, writes static/library/<id>.glb (or volume).\n' +
      ' - Library cards: <img> thumbnail, then on click fetch /api/library/<id>.glb ' +
      '→ Three.js GLTFLoader → GPU upload. No WASM in the page at all.\n\n' +
      '**2. Edit (/author) — Apply-on-demand GLBs:**\n' +
      ' - Slider changes are local (UI only, no rebuild).\n' +
      ' - User clicks Apply → POST /api/author/build { spec } → server runs CSG, ' +
      'caches by content hash (e.g. <sha256(spec)>.glb), returns the URL.\n' +
      ' - Client GLTFLoads the URL just like the library path.\n' +
      ' - Same params from a different user = HTTP 304 / browser cache hit, ' +
      'zero new server work.\n\n' +
      'Why this is the right architecture:\n' +
      ' - Server heap is ~unbounded vs mobile Safari ~1GB cap → can use any segment ' +
      'count, fuse any number of parts, no peak-memory dance\n' +
      ' - GLBs are CDN-friendly, cacheable, ~1-5MB each, fast to serve\n' +
      ' - Removes the multi-mesh trick from F.122 — server can fuse to one mesh ' +
      "if that's better for a given assembly\n" +
      ' - Decouples build complexity from device — same GLB renders identically ' +
      'on iPhone and desktop\n\n' +
      'Trade-offs:\n' +
      ' - No live-slider preview in /author — Apply is explicit (could mitigate ' +
      'with a 500ms-debounced auto-Apply once latency is measured)\n' +
      ' - Apply round-trip ~200-800ms (Node CSG + GLB serialize + transfer) ' +
      "vs instant local — fine for deliberate edits, less for jog-the-slider " +
      'exploration\n' +
      ' - First-render of an uncached spec pays full CSG cost; subsequent loads ' +
      'are HTTP cache hits\n\n' +
      'Open design questions:\n' +
      ' - Where does the build queue live? Inline in /api/author/build (simple, ' +
      'blocks the request for 3-10s) or a job queue (BullMQ + Redis, async, but ' +
      'adds infrastructure)?\n' +
      ' - Cache invalidation: bumping builder.ts geometry invalidates every GLB. ' +
      'Add a builder-version hash to the filename and let old ones expire.\n' +
      ' - Storage: static/ for committed library GLBs, volume for Apply cache (it ' +
      'grows unboundedly).',
  },

  124: {
    summary:
      'Speculative future work: GPU-based CSG (compute-shader Booleans) for the ' +
      'giant-mesh path. Today buildAuthored() avoids OOM by NOT fusing all parts. ' +
      'But there are real assemblies where you want one fused manifold (e.g. for ' +
      'export to STEP, for downstream FEA, for accurate vertex coloring across ' +
      'merged surfaces). WASM CSG hits the heap ceiling on those.\n\n' +
      'GPU CSG approaches to evaluate:\n' +
      ' - threejs-csg (uses BSP trees on CPU — same problem as Manifold)\n' +
      ' - manifold-3d itself with WebGPU backend (open issue, not shipped)\n' +
      ' - Voxel-based CSG (rasterize each mesh into a 3D texture, do boolean ops ' +
      "as fragment-shader passes, marching-cubes back to mesh — fast but loses " +
      'sharp edges)\n' +
      ' - Mesh-Boolean libraries that target WebGPU compute shaders (active ' +
      'research, e.g. Apple/NVIDIA papers)\n\n' +
      'Out of scope for current iteration. Worth revisiting once the rest of the ' +
      'product is settled.',
  },

  // ───── G. Vendor catalog ingest ─────

  200: {
    summary:
      'Convention established: vendor catalog PDFs live under static/eval/catalog/<vendor>/. ' +
      'A manifest.json per vendor lists chapters with title, page_count, indexed status. ' +
      'PDFs themselves are gitignored (large + license-uncertain) but the directory + ' +
      'manifest are committed so the indexer code knows what to expect. First entry: ' +
      'Halliburton 06_Packers (86 pages).',
    refs: ['static/eval/catalog/halliburton/manifest.json'],
  },

  201: {
    summary:
      'scripts/inspect_catalog_pdf.py walks every page of a vendor PDF and emits ' +
      '<basename>.inspect.json next to it. Per page it counts: drawing paths ' +
      '(page.get_drawings), embedded raster images (page.get_images), and text blocks ' +
      "(page.get_text('blocks')). Each page is classified into one of: cover | text_only | " +
      'spec_table | mixed_schematic | photo_set | unknown.\n\n' +
      'Halliburton 06_Packers (86 pages) classified as: 66 mixed_schematic, ' +
      '19 photo_set, 1 unknown (back cover with logo, 15 paths just under threshold). ' +
      'No covers/spec_tables/text_only — the chapter is uniformly engineering content. ' +
      'Output written to static/eval/catalog/halliburton/06_Packers.inspect.json with ' +
      'thresholds + per-page raw counts so downstream extractors (G.2 SVG, G.3 spec-table, ' +
      'G.4 labeled schematic) know which pages to process.\n\n' +
      'Note: the inspector is local-only Python (PyMuPDF), invoked outside the production ' +
      "app. Per CLAUDE.md rule 'no Python in the production container' — this is offline " +
      'tooling that produces a committed JSON artifact, then never runs in prod.',
    steps: [
      'scripts/inspect_catalog_pdf.py with classify_page() heuristic + THRESHOLDS dict',
      'Run against static/eval/catalog/halliburton/06_Packers.pdf',
      'Output: static/eval/catalog/halliburton/06_Packers.inspect.json (committed)',
    ],
    acceptance: [
      'Inspect JSON exists with one entry per page',
      'Counts (paths/images/text_blocks) match what PyMuPDF reports',
      'Class buckets sum to page_count (86)',
      'No engine pages misclassified as cover (covers should be near-empty)',
    ],
    refs: [
      'scripts/inspect_catalog_pdf.py',
      'static/eval/catalog/halliburton/06_Packers.inspect.json',
    ],
  },

  202: {
    summary:
      'Pull vector schematics (Perma-Series cross-sections, assembly diagrams) out as ' +
      'clean SVG. PyMuPDF gives the path stack; we re-emit as SVG preserving stroke/fill, ' +
      'normalize coordinates to 0-1000 range, and embed any text labels with their bbox ' +
      'so downstream code can match labels to parts (G.4).',
    acceptance: [
      'Page 4 (Wireline-Set Perma-Series cross-section) extracts as SVG',
      'Bottom Sub photographs on the same page route to raster (skipped by SVG extractor)',
      'Output: static/eval/catalog/halliburton/06_packers/p4.svg',
    ],
  },

  203: {
    summary:
      'Halliburton spec tables are dense but regular: casing_size, packer_od, sealbore_id, ' +
      'seal_unit_id × N rows. Extract via text-block grouping + grid-line detection. ' +
      'Output JSON validates: each row\'s OD ∈ existing primitive param ranges (or expands ' +
      'them if the catalog reveals real-world values outside our assumed bounds).',
    acceptance: [
      'p.6 (Wireline-Set Perma-Series specs) → 50+ rows of JSON',
      'Spec ranges fed back to src/lib/cad/library.ts param min/max if needed',
    ],
  },

  204: {
    summary:
      'Cross-section diagrams (e.g., page 4 of Packers) have leader lines connecting text ' +
      'labels ("Upper Internal Slips", "Triple-Seal Multidurometer Elements", etc.) to ' +
      'specific regions of the schematic. Extract this as a graph: { label_text, label_bbox, ' +
      'line_path, target_part_bbox }. Becomes ground truth for the assembly segmentation work ' +
      '(prior plan B.x) — we now have real labeled examples instead of synthetic-only.',
    acceptance: [
      'Page 4 yields ≥9 labeled parts (matches the 9 callouts on the schematic)',
      'JSON loads into a viewer that renders the SVG with hoverable labels',
    ],
  },

  205: {
    summary:
      'Replace the 1,646 HAL_PACKERS + HAL_WPS records currently in cache.jsonl with ' +
      'component_id="unknown" with proper labels derived from G.2-G.4 extraction. New ' +
      'records carry: component_id (mapped to the cadtrain 18-primitive taxonomy), ' +
      'vendor_model_id (e.g., "Perma-Series-AWB"), source="catalog_v2", page_ref, ' +
      'CLIP embedding (re-computed). Old "unknown" records archived to cache.jsonl.bak.',
    acceptance: [
      'Cache /api/cache/stats shows >0 records with vendor_model_id',
      '/archive/reverse retrieval surfaces real catalog matches with named labels',
    ],
  },

  206: {
    summary:
      'Browse vendor catalogs in-app at /cad/catalog/halliburton/06_packers — per-page ' +
      'viewer with three toggles: raster (original render), SVG (extracted paths), and ' +
      'overlay (label graph from G.4 superimposed on the SVG). Useful for QA-ing the ' +
      'extraction pipeline and as a reference catalog for users.',
  },

  207: {
    summary:
      'Once both authored cadtrain components and vendor model entries exist, allow ' +
      'authors to tag their compositions with the vendor model they\'re replicating ' +
      '(e.g., authored "perma_lach_pls" → tagged "Halliburton PLS Mechanical-Set Double ' +
      'Grip"). Enables vendor-aware retrieval ("show me everything we have authored ' +
      'for HAL Versa-Trieve") and seeds the spatial-grammar work in B.x.',
  },
};
