/**
 * Detail records for /plan task popups. Keyed by task `id` from
 * +page.svelte. Add an entry only when there's enough substance to
 * warrant the popup; the page falls back to "no detail entry yet"
 * when missing.
 */

export interface PlanDetail {
  summary?: string;
  steps?: string[];
  acceptance?: string[];
  refs?: string[];
  /**
   * Recording of the e2e suite that verifies this task's work, per
   * CLAUDE.md Rule 12. Path is relative to /static/, e.g.
   * `/api/volume?path=test-recordings/e2e/115/routes.webm`. The Gantt popup renders an inline
   * <video controls> when set. Multiple recordings: pass the manifest
   * path instead (`/api/volume?path=test-recordings/e2e/<task>/manifest.json`) and the popup
   * lists each spec.
   *
   * Generated by: `bun run record:task -- <id>`
   * which runs `scripts/harvest_e2e_videos.ts`.
   */
  video?: string;
  videos?: string[];
  /**
   * Explicit "no recording expected" marker for docs-only or trivial
   * tasks where Rule 12's per-step e2e recording doesn't apply. Lets a
   * future reader distinguish "deliberately not recorded" from
   * "recording owed but missing".
   */
  recorded?: boolean;
}

export const details: Record<number, PlanDetail> = {
  // ───── Remaining build work ─────

  512: {
    summary:
      'AI refine — Level 2: post-generation validation in the refine endpoint.\n\n' +
      'After Claude returns, run these gates BEFORE shipping the proposal back to ' +
      'the client:\n\n' +
      '(a) **Imports allowlist** — only `\'../manifold-helpers\'`, `\'.\'`, ' +
      '`\'./<sibling-id>\'`. Mirror parseImports() in component-loader.ts.\n' +
      '(b) **Denylist scan** — reject `require(` / `process` / `import(` / ' +
      '`eval(` / `Function(` in the body. Mirror the loader denylist.\n' +
      '(c) **Undefined-instance detection** — for every `<INST>.<prop>` in the geom ' +
      'body, verify `<INST>` was declared earlier as `let|const <INST> = call(...)`. ' +
      'This is the most common AI failure mode: removing an instance but leaving its ' +
      '.length / .top reference behind.\n' +
      '(d) **Syntax check** — via `checkTypescriptSyntax` (already exists in the ' +
      'client; expose for server use or recreate via Prettier).\n' +
      '(e) **Optional live-bake** — call `buildGlbBytes` to verify it produces ' +
      'geometry. Cheap gate against malformed accumulator chains.\n\n' +
      'On any failure, retry ONCE with the validation errors fed back in the user ' +
      'message. After 2 failures, return `{ ok: false, error, validationFailures: ' +
      'string[] }` and surface it in the inspector UI.',
    acceptance: [
      'A proposal that references a non-existent instance is rejected by the endpoint with a clear error, NOT returned to the user with a "memory access out of bounds" later',
      'Unit test covers the undefined-instance case',
      'Disallowed imports / denylisted globals trigger validation failure with the offending line',
      'Endpoint retries once with validation feedback before giving up',
    ],
    refs: [
      'src/routes/api/components/refine/+server.ts',
      'src/lib/server/component-loader.ts (mirror parseImports + denylist)',
      'src/lib/server/refine-validate.ts (new — proposed location)',
    ],
    recorded: false,
  },

  513: {
    summary:
      'AI refine — Level 3: live-bake gate on the Accept button.\n\n' +
      'In the inspector AI tab (in src/routes/components/+page.svelte), when an AI ' +
      'proposal arrives, fire a bake-preview against the proposed source + current ' +
      'params. Render a small status pill next to the Accept button:\n\n' +
      ' - ✓ "Builds (X positions)" — green\n' +
      ' - ✗ "Bake failed: <message>" — red, Accept disabled\n\n' +
      'Grey out Accept when bake fails — force the user to either retry or reject ' +
      'rather than accept code that won\'t render. The bake-preview endpoint already ' +
      'exists (added this session): POST /api/components/bake-preview with ' +
      '{ id, source, params } returns GLB bytes or 4xx with a message.',
    acceptance: [
      'A proposal that the AI returns but bake-preview rejects shows the user a red status pill; Accept is disabled',
      'A working proposal shows green and Accept is enabled',
      'No backend changes — purely a UI gate on top of the existing bake-preview endpoint',
    ],
    refs: [
      'src/routes/components/+page.svelte (AI inspector tab + Accept button)',
      'src/routes/api/components/bake-preview/+server.ts (existing endpoint)',
    ],
    recorded: false,
  },

  514: {
    summary:
      'AI refine — Level 4: assembly-aware refine prompt.\n\n' +
      'When the AI refines a COMPOSITION (a part that imports multiple sibling ' +
      'components), include the relevant recipe docs from docs/assemblies/ in the ' +
      'system prompt:\n\n' +
      ' - docs/assemblies/README.md — the recipe-writing rules.\n' +
      ' - Each matching <assembly>.md — matching is by mentioning the assembly name ' +
      'in the part\'s meta.name or by the part importing a known recipe\'s ' +
      'primitives.\n\n' +
      'Today nothing in src/ reads docs/assemblies/ (grep-verified) — the AI is ' +
      'blind to existing assembly conventions and re-invents them every refine.',
    acceptance: [
      'A refine on a known assembly (e.g. tubing_hanger_spool_stack) loads its .md into the prompt',
      'The AI\'s proposal respects the stack diagram + key dimensions documented in the recipe',
      'README.md rules (e.g. "list components top-down with z offsets") are visible in the system message',
    ],
    refs: [
      'src/routes/api/components/refine/+server.ts (buildSystemPrompt — extend with assembly glob)',
      'docs/assemblies/README.md',
      'docs/assemblies/_TEMPLATE.md',
      'docs/assemblies/tubing_hanger_spool_stack.md (first worked example)',
    ],
    recorded: false,
  },

  // ───── /wells — editing + 3D-fast build architecture (design 2026-07-04) ─────

  951: {
    summary:
      'W-B1 · Editing — mutation + undo layer (the viewer→editor foundation).\n\n' +
      'ewells.app (= SVTC) is a VIEWER; the differentiator for /wells is turning ' +
      'the schematic into an EDITOR. This task builds the substrate every editor ' +
      'panel writes through:\n\n' +
      ' - A single `commit(mutation)` choke point that applies a structured edit ' +
      'to the open .wson (add/remove/edit casing·tubing·cement·completion strings, ' +
      'survey stations, perfs) and produces a new immutable well state.\n' +
      ' - A per-workspace undo/redo history stack over those commits.\n' +
      ' - Change notification that triggers the 3D re-bake (via the WellBakePool, ' +
      '#957) + the 2D SVG re-render, both already reactive.\n\n' +
      'Prereq for CompletionsEditor (#960), SurveyEditor (#961), inspector-on-select ' +
      '(#962). SSR-safe.',
    acceptance: [
      'An edit to a string OD updates both the 2D SVG and the 3D view',
      'Undo/redo restores prior well state exactly',
      'No panel mutates the .wson directly — everything goes through commit()',
    ],
    refs: [
      'docs/plans/wells-ewells-gaps.md (§B editing)',
      'src/lib/wells/ (engine — mutation helpers)',
      'src/routes/wells/+page.svelte (workspace + undo history)',
    ],
    recorded: false,
  },

  957: {
    summary:
      'W-H1 · 3D-fast build — WellBakePool.\n\n' +
      'ROOT CAUSE (docs/research/wells-perf-ewells-vs-cadtrain.md): ewells draws an ' +
      'instant 2D SVG; /wells built real watertight Manifold CSG shells + a ' +
      'per-element half-section cutaway SYNCHRONOUSLY on the MAIN THREAD, then bent ' +
      'each along the survey in a per-vertex JS loop → the UI janked on long/multi-' +
      'string wells. Shipping the 2D-SVG-default (#953) hid this for tab-open; this ' +
      'task fixes the 3D path itself.\n\n' +
      'Move the per-element build into a POOL of N Web-Workers, each owning its OWN ' +
      'Manifold instance (crucially NOT the /primitives editor\'s single latest-wins ' +
      'worker — wells needs ALL elements built in parallel, cached, and rendered ' +
      'progressively). Rides the existing bake-worker / bake-client pipeline ' +
      '(client_side_execution).',
    acceptance: [
      'Opening a long multi-string well in 3D no longer blocks the UI thread',
      'Elements appear progressively as their workers finish',
      'Per-element bake results are cached (no rebuild on unrelated edits)',
    ],
    refs: [
      'docs/plans/wells-build-architecture.md (P1–P3, WellBakePool)',
      'src/lib/cad/bake-worker.ts + bake-client.ts (reused pipeline)',
      'src/lib/wells/WellSchematic3D.svelte (the main-thread $derived.by stack to move off-thread)',
    ],
    recorded: false,
  },

  958: {
    summary:
      'W-H2 · 3D-fast — clip-plane cutaway (drop the boolean).\n\n' +
      'The half-section cutaway is currently a per-element Manifold `.cut()` boolean. ' +
      'CSG cutaway scales super-linearly (memory stack_cutaway_perf_root_cause) and ' +
      're-triggers a full rebuild on every azimuth / toggle change. Replace it with a ' +
      'GPU clip plane: THREE material `clippingPlanes` + a stencil-pass to cap the ' +
      'cut faces. Then the cutaway is free at render time and never touches the CSG ' +
      'kernel — azimuth becomes a live slider.',
    acceptance: [
      'Toggling cutaway / rotating the cut azimuth is instant (no rebake)',
      'Cut faces are capped (not hollow) via the stencil pass',
      'Matches the current boolean cutaway visually',
    ],
    refs: [
      'docs/plans/wells-build-architecture.md (clip-plane cutaway)',
      'src/lib/wells/WellSchematic3D.svelte (current .cut() half-section)',
    ],
    recorded: false,
  },

  959: {
    summary:
      'W-H3 · Parametric element libraries.\n\n' +
      'The well elements (open-hole / casing / tubing / cement / perf) become ' +
      'PARAMETRIC LIBRARY parts the wells engine CALLS procedurally, and completions ' +
      'become the g_* jewelry parts baked via compile + worker. Register the g_* ' +
      'parts into the parametric registry with ParamSpec dials — this is what the ' +
      'W-B4 inspector (#962) reads to build its editing UI. Adds auto-scale/fit.',
    acceptance: [
      'Each element type resolves to a parametric library part with a ParamSpec',
      'g_* completions are registered + selectable + bakeable via the worker',
      'Auto-scale fits the whole string to the viewport',
    ],
    refs: [
      'docs/plans/wells-build-architecture.md (§A2 element libraries)',
      'docs/plans/wells-ewells-gaps.md (§A2)',
      'src/lib/wells/ (engine registry)',
    ],
    recorded: false,
  },

  // ───── TF / revolve follow-ups (from the 2026-07-06/07 batch) ─────

  944: {
    summary:
      'Curvature-adaptive warp axial span.\n\n' +
      'Route C lean revolve (#942) re-densifies a warped part at build time via a ' +
      'CONSTANT axial span dial (_axialMaxZSpan = 1.5) so a warped shaft samples enough ' +
      'Z-stations to bend smoothly. A constant span over-tessellates long, gently-curved ' +
      'wells (lots of stations where the trajectory is nearly straight). Replace the ' +
      'constant with a planAxialStations() pass that places stations by LOCAL CURVATURE ' +
      '— dense through doglegs, sparse on straight runs — so vert counts track the actual ' +
      'geometry. Rule-25 clean (build-time segmentation, never a post-bake mesh rewrite).',
    acceptance: [
      'A long, near-straight warped well samples far fewer axial stations than the constant span',
      'A tight dogleg keeps enough stations to stay smooth (no faceting)',
      'Build-time only — no post-bake MeshGL subdivide (Rule 25)',
    ],
    refs: [
      'docs/plans/manifold-revolve-lean.md',
      'docs/plans/curvature-adaptive-warp-subdivision.md',
      'src/lib/cad/bake-worker-core.ts (_axialMaxZSpan dial)',
    ],
    recorded: false,
  },

  945: {
    summary:
      '/api/tf/compile — parallelize the BFS dep frontier + save-invalidation.\n\n' +
      'Two follow-ups on the TF compile cache shipped 2026-07-06:\n' +
      ' (a) The dep-resolution BFS walks the frontier serially; fan each frontier level ' +
      'out in parallel so a deep dep tree compiles in one round-trip per LEVEL, not per node.\n' +
      ' (b) On part Save, INVALIDATE the dep-source caches that reference it so a ' +
      'cross-part edit shows up instantly instead of waiting out the 30-60s TTL.',
    acceptance: [
      'A deep dep tree compiles noticeably faster (parallel frontier)',
      'Editing a dependency part reflects in dependents immediately after Save (no TTL wait)',
    ],
    refs: [
      'docs/plans/tf-compile-perf.md',
      'src/routes/api/tf/compile/+server.ts',
    ],
    recorded: false,
  },

  946: {
    summary:
      'TF_WASM tab — C++→WASM TrueForm builders.\n\n' +
      'A tab that runs the TrueForm builders compiled from C++ to WASM. IMPORTANT honest ' +
      'framing: the reason the TF tab is fast is that it runs in a WEB WORKER (off the ' +
      'main thread), NOT because of the language. Compiling to WASM here buys SOURCE ' +
      'CONCEALMENT (ship builders as opaque WASM), not raw speed. Order this after the TF ' +
      'tab + compile-perf work stabilizes.',
    acceptance: [
      'TF builders run from a WASM module in the worker',
      'Builder source is not shipped as readable JS',
    ],
    refs: [
      'docs/plans/tf-wasm-tab.md',
    ],
    recorded: false,
  },

  947: {
    summary:
      'Per-SUBPART material — color-by-source.\n\n' +
      'The TF hardening (#942) shipped per-PART material on the full + cut views. But a ' +
      'material set on a HIDDEN sub-part is currently lost when subparts are merged into ' +
      'the full + cut meshes. Needs color-by-source: track which source part each merged ' +
      'triangle came from so a subpart\'s material survives the merge.',
    acceptance: [
      'A material on a hidden sub-part is honored in both the full and the cut mesh',
      'Merged meshes carry per-source material groups',
    ],
    refs: [
      'src/lib/cad/tf-worker-core.ts (per-part material + merge)',
      'memory: session_handoff_2026-07-06',
    ],
    recorded: false,
  },

  948: {
    summary:
      'Warp-trajectory originZ + #38 P2 param-editor tails (from the 2026-07-07 batch, ' +
      '#972). The parts_map NODE-CARD + pm_demo volume part shipped separately — see #973. ' +
      'What is LEFT:\n\n' +
      ' #36c — the warp spline tangent-extension to ±∞ shipped; the originZ PLACEMENT ' +
      'option exists in warp-spline.ts but NO caller feeds it through to the warp node. ' +
      'Wire it.\n' +
      ' #38 P2 — the ParamsCard list<record> TABLE editor (the "add object / add row" ' +
      'param editor) for the new record|list param kinds. P1 (ParamSchema discriminated ' +
      'union number|record|list), P3 (parts_map producer + the bakeable pm_demo), and the ' +
      'parts_map node-card (#973) all shipped — this is the remaining param-authoring UI.',
    acceptance: [
      'The warp node exposes + applies the originZ placement option',
      'A record/list param is authored + edited from the ParamsCard table editor (add object / add row)',
    ],
    refs: [
      'docs/plans/warp-part-along-spline.md (items: originZ wiring)',
      'docs/plans/complex-params-list-of-parts.md',
      'docs/plans/parts-params.md',
      'src/lib/cad/nodes/kinds/parts-map.ts (P3, shipped)',
    ],
    recorded: false,
  },

  973: {
    summary:
      'parts_map GEP node-card + pm_demo live volume part — SHIPPED 2026-07-07 (bdc2595).\n\n' +
      'The authoring surface for the #38 data-driven-params work: a graph node that maps a ' +
      'list<record> → N part instances, editable directly in the graph editor.\n\n' +
      ' • NodeCard.svelte — a VIOLET parts_map branch (src part · rows source · arg→field ' +
      'binding rows · list/stack/place op toggle · output socket · delete).\n' +
      ' • composition-graph-mutate.ts — addPartsMap + setPartsMapSrc/List/Arg/Op + ' +
      'add/removePartsMapArg.\n' +
      ' • GraphEditorPane.svelte — dropPartsMap + the ✎ → container → parts_map picker item.\n\n' +
      'Plus pm_demo promoted to a LIVE VOLUME PART (basic/pm_demo.asm.ts, bakes 3 solids) — ' +
      'not just the golden fixture. Split out of the old #948 tail; what remains there is the ' +
      'P2 ParamsCard table editor + a TF parts_map builder (#974).',
    acceptance: [
      'A parts_map node can be dropped, wired to a list<record>, and bound arg→field in the editor',
      'pm_demo resolves as a volume part and bakes 3 solids',
    ],
    refs: [
      'src/lib/shared/graph-editor/NodeCard.svelte (parts_map branch)',
      'src/lib/cad/composition-graph-mutate.ts (addPartsMap + setters)',
      'src/lib/shared/graph-editor/GraphEditorPane.svelte (dropPartsMap + picker)',
      'src/lib/cad/nodes/kinds/parts-map.ts',
    ],
    recorded: false,
  },

  974: {
    summary:
      'TF parts_map builder.\n\n' +
      'The TF (native-only) engine cannot build a parts_map node yet: graph-to-tf.ts has NO ' +
      'parts_map case, so the node falls through to the default branch → ' +
      'UNSUPPORTED ("node <id>: type \'parts_map\' has no TF mapping") and the tab reports no ' +
      'builder for it. Add a lowerNode case that expands the list<record> producer into N ' +
      'transformed part instances (union / stack / place per the node\'s op), mirroring the ' +
      'Manifold executeTfRecipe path, so a pm_demo-style part builds NATIVELY in TF. Extends ' +
      'the parts_map node-card (#973) + the r_weld_extrude / composite TF builders (#942).',
    acceptance: [
      'A parts_map node lowers to a TF recipe (no UNSUPPORTED note)',
      'pm_demo builds natively in the TF tab (3 solids, not blank)',
    ],
    refs: [
      'src/lib/cad/graph-to-tf.ts (add the parts_map lowerNode case)',
      'src/lib/cad/nodes/kinds/parts-map.ts',
    ],
    recorded: false,
  },
};
