// AUTO-GENERATED by scripts/gen-folder-tree.mjs — do not edit by hand.
// Snapshot of the src/ tree with per-file line counts (LOC), for the
// /design "Folder tree" hierarchy views. Regenerate with:
//   bun scripts/gen-folder-tree.mjs      (this file alone)
//   bun scripts/gen-design-diagrams.mjs  (all three /design snapshots)
// Stats at generation: 419 files · 91 folders · 93,783 LOC.

export interface FolderNode {
  name: string;
  path: string;
  loc?: number;
  children?: FolderNode[];
}

export const FOLDER_TREE_STATS = { files: 419, folders: 91, loc: 93783 } as const;

export const FOLDER_TREE: FolderNode = {
  "name": "src",
  "path": "src",
  "children": [
    {
      "name": "lib",
      "path": "src/lib",
      "children": [
        {
          "name": "authoring",
          "path": "src/lib/authoring",
          "children": [
            {
              "name": "compjson-to-profile.ts",
              "path": "src/lib/authoring/compjson-to-profile.ts",
              "loc": 306
            },
            {
              "name": "proposal-translator.ts",
              "path": "src/lib/authoring/proposal-translator.ts",
              "loc": 167
            },
            {
              "name": "rule-translator-graph.test.ts",
              "path": "src/lib/authoring/rule-translator-graph.test.ts",
              "loc": 100
            },
            {
              "name": "rule-translator.ts",
              "path": "src/lib/authoring/rule-translator.ts",
              "loc": 588
            }
          ]
        },
        {
          "name": "cad",
          "path": "src/lib/cad",
          "children": [
            {
              "name": "nodes",
              "path": "src/lib/cad/nodes",
              "children": [
                {
                  "name": "kinds",
                  "path": "src/lib/cad/nodes/kinds",
                  "children": [
                    {
                      "name": "call.test.ts",
                      "path": "src/lib/cad/nodes/kinds/call.test.ts",
                      "loc": 44
                    },
                    {
                      "name": "call.ts",
                      "path": "src/lib/cad/nodes/kinds/call.ts",
                      "loc": 32
                    },
                    {
                      "name": "container-stack.test.ts",
                      "path": "src/lib/cad/nodes/kinds/container-stack.test.ts",
                      "loc": 78
                    },
                    {
                      "name": "container.ts",
                      "path": "src/lib/cad/nodes/kinds/container.ts",
                      "loc": 41
                    },
                    {
                      "name": "expr.ts",
                      "path": "src/lib/cad/nodes/kinds/expr.ts",
                      "loc": 39
                    },
                    {
                      "name": "index.ts",
                      "path": "src/lib/cad/nodes/kinds/index.ts",
                      "loc": 19
                    },
                    {
                      "name": "material.test.ts",
                      "path": "src/lib/cad/nodes/kinds/material.test.ts",
                      "loc": 33
                    },
                    {
                      "name": "material.ts",
                      "path": "src/lib/cad/nodes/kinds/material.ts",
                      "loc": 19
                    },
                    {
                      "name": "method.test.ts",
                      "path": "src/lib/cad/nodes/kinds/method.test.ts",
                      "loc": 33
                    },
                    {
                      "name": "method.ts",
                      "path": "src/lib/cad/nodes/kinds/method.ts",
                      "loc": 21
                    },
                    {
                      "name": "mv-rot.test.ts",
                      "path": "src/lib/cad/nodes/kinds/mv-rot.test.ts",
                      "loc": 43
                    },
                    {
                      "name": "mv.ts",
                      "path": "src/lib/cad/nodes/kinds/mv.ts",
                      "loc": 20
                    },
                    {
                      "name": "poly-repeat.ts",
                      "path": "src/lib/cad/nodes/kinds/poly-repeat.ts",
                      "loc": 24
                    },
                    {
                      "name": "polygon.test.ts",
                      "path": "src/lib/cad/nodes/kinds/polygon.test.ts",
                      "loc": 72
                    },
                    {
                      "name": "polygon.ts",
                      "path": "src/lib/cad/nodes/kinds/polygon.ts",
                      "loc": 77
                    },
                    {
                      "name": "repeat.test.ts",
                      "path": "src/lib/cad/nodes/kinds/repeat.test.ts",
                      "loc": 65
                    },
                    {
                      "name": "repeat.ts",
                      "path": "src/lib/cad/nodes/kinds/repeat.ts",
                      "loc": 106
                    },
                    {
                      "name": "rot.ts",
                      "path": "src/lib/cad/nodes/kinds/rot.ts",
                      "loc": 20
                    },
                    {
                      "name": "sketch-expr.test.ts",
                      "path": "src/lib/cad/nodes/kinds/sketch-expr.test.ts",
                      "loc": 105
                    },
                    {
                      "name": "sketch-repeat.ts",
                      "path": "src/lib/cad/nodes/kinds/sketch-repeat.ts",
                      "loc": 27
                    },
                    {
                      "name": "sketch.ts",
                      "path": "src/lib/cad/nodes/kinds/sketch.ts",
                      "loc": 119
                    },
                    {
                      "name": "spline-warp.test.ts",
                      "path": "src/lib/cad/nodes/kinds/spline-warp.test.ts",
                      "loc": 48
                    },
                    {
                      "name": "spline.ts",
                      "path": "src/lib/cad/nodes/kinds/spline.ts",
                      "loc": 18
                    },
                    {
                      "name": "stack.ts",
                      "path": "src/lib/cad/nodes/kinds/stack.ts",
                      "loc": 54
                    },
                    {
                      "name": "txfmn.test.ts",
                      "path": "src/lib/cad/nodes/kinds/txfmn.test.ts",
                      "loc": 55
                    },
                    {
                      "name": "txfmn.ts",
                      "path": "src/lib/cad/nodes/kinds/txfmn.ts",
                      "loc": 31
                    },
                    {
                      "name": "warp.ts",
                      "path": "src/lib/cad/nodes/kinds/warp.ts",
                      "loc": 30
                    }
                  ]
                },
                {
                  "name": "emit-golden.test.ts",
                  "path": "src/lib/cad/nodes/emit-golden.test.ts",
                  "loc": 106
                },
                {
                  "name": "node-kind.ts",
                  "path": "src/lib/cad/nodes/node-kind.ts",
                  "loc": 146
                },
                {
                  "name": "registry.ts",
                  "path": "src/lib/cad/nodes/registry.ts",
                  "loc": 38
                }
              ]
            },
            {
              "name": "stdlib",
              "path": "src/lib/cad/stdlib",
              "children": [
                {
                  "name": "stale",
                  "path": "src/lib/cad/stdlib/stale",
                  "children": [
                    {
                      "name": "r_extrude.ts",
                      "path": "src/lib/cad/stdlib/stale/r_extrude.ts",
                      "loc": 107
                    }
                  ]
                },
                {
                  "name": "r_cuboid.ts",
                  "path": "src/lib/cad/stdlib/r_cuboid.ts",
                  "loc": 48
                },
                {
                  "name": "r_helical_surface.ts",
                  "path": "src/lib/cad/stdlib/r_helical_surface.ts",
                  "loc": 199
                },
                {
                  "name": "r_loft.ts",
                  "path": "src/lib/cad/stdlib/r_loft.ts",
                  "loc": 160
                },
                {
                  "name": "r_revolve.test.ts",
                  "path": "src/lib/cad/stdlib/r_revolve.test.ts",
                  "loc": 222
                },
                {
                  "name": "r_revolve.ts",
                  "path": "src/lib/cad/stdlib/r_revolve.ts",
                  "loc": 212
                },
                {
                  "name": "r_surface.ts",
                  "path": "src/lib/cad/stdlib/r_surface.ts",
                  "loc": 161
                },
                {
                  "name": "r_sweep.ts",
                  "path": "src/lib/cad/stdlib/r_sweep.ts",
                  "loc": 116
                },
                {
                  "name": "r_weld_extrude.ts",
                  "path": "src/lib/cad/stdlib/r_weld_extrude.ts",
                  "loc": 139
                }
              ]
            },
            {
              "name": "__spline_bake_verify.test.ts",
              "path": "src/lib/cad/__spline_bake_verify.test.ts",
              "loc": 76
            },
            {
              "name": "__spline_closed_verify.test.ts",
              "path": "src/lib/cad/__spline_closed_verify.test.ts",
              "loc": 121
            },
            {
              "name": "__spline_plot_flag.test.ts",
              "path": "src/lib/cad/__spline_plot_flag.test.ts",
              "loc": 61
            },
            {
              "name": "__spline_pointsexpr_bake.test.ts",
              "path": "src/lib/cad/__spline_pointsexpr_bake.test.ts",
              "loc": 64
            },
            {
              "name": "__spline_pointsexpr_verify.test.ts",
              "path": "src/lib/cad/__spline_pointsexpr_verify.test.ts",
              "loc": 65
            },
            {
              "name": "annular-sweep.test.ts",
              "path": "src/lib/cad/annular-sweep.test.ts",
              "loc": 152
            },
            {
              "name": "bake-client.ts",
              "path": "src/lib/cad/bake-client.ts",
              "loc": 244
            },
            {
              "name": "bake-worker-core.test.ts",
              "path": "src/lib/cad/bake-worker-core.test.ts",
              "loc": 131
            },
            {
              "name": "bake-worker-core.ts",
              "path": "src/lib/cad/bake-worker-core.ts",
              "loc": 297
            },
            {
              "name": "bake-worker.ts",
              "path": "src/lib/cad/bake-worker.ts",
              "loc": 66
            },
            {
              "name": "client-bake-color-by-source.test.ts",
              "path": "src/lib/cad/client-bake-color-by-source.test.ts",
              "loc": 101
            },
            {
              "name": "composition-bake.ts",
              "path": "src/lib/cad/composition-bake.ts",
              "loc": 100
            },
            {
              "name": "composition-emit-profile.ts",
              "path": "src/lib/cad/composition-emit-profile.ts",
              "loc": 273
            },
            {
              "name": "composition-emit.ts",
              "path": "src/lib/cad/composition-emit.ts",
              "loc": 778
            },
            {
              "name": "composition-graph-hydrate.ts",
              "path": "src/lib/cad/composition-graph-hydrate.ts",
              "loc": 474
            },
            {
              "name": "composition-graph-mutate.ts",
              "path": "src/lib/cad/composition-graph-mutate.ts",
              "loc": 2253
            },
            {
              "name": "composition-graph-types.ts",
              "path": "src/lib/cad/composition-graph-types.ts",
              "loc": 655
            },
            {
              "name": "composition-graph.test.ts",
              "path": "src/lib/cad/composition-graph.test.ts",
              "loc": 702
            },
            {
              "name": "composition-graph.ts",
              "path": "src/lib/cad/composition-graph.ts",
              "loc": 28
            },
            {
              "name": "composition-layout.test.ts",
              "path": "src/lib/cad/composition-layout.test.ts",
              "loc": 366
            },
            {
              "name": "composition-layout.ts",
              "path": "src/lib/cad/composition-layout.ts",
              "loc": 475
            },
            {
              "name": "composition-material.test.ts",
              "path": "src/lib/cad/composition-material.test.ts",
              "loc": 126
            },
            {
              "name": "composition-tree.test.ts",
              "path": "src/lib/cad/composition-tree.test.ts",
              "loc": 118
            },
            {
              "name": "composition-tree.ts",
              "path": "src/lib/cad/composition-tree.ts",
              "loc": 799
            },
            {
              "name": "crease-normals.test.ts",
              "path": "src/lib/cad/crease-normals.test.ts",
              "loc": 282
            },
            {
              "name": "csg-2d.ts",
              "path": "src/lib/cad/csg-2d.ts",
              "loc": 137
            },
            {
              "name": "cutaway-perbody-skip.test.ts",
              "path": "src/lib/cad/cutaway-perbody-skip.test.ts",
              "loc": 61
            },
            {
              "name": "editor-tools-schema.ts",
              "path": "src/lib/cad/editor-tools-schema.ts",
              "loc": 268
            },
            {
              "name": "editor-tools.test.ts",
              "path": "src/lib/cad/editor-tools.test.ts",
              "loc": 162
            },
            {
              "name": "editor-tools.ts",
              "path": "src/lib/cad/editor-tools.ts",
              "loc": 295
            },
            {
              "name": "expr-emit.test.ts",
              "path": "src/lib/cad/expr-emit.test.ts",
              "loc": 265
            },
            {
              "name": "expr-imperative.test.ts",
              "path": "src/lib/cad/expr-imperative.test.ts",
              "loc": 330
            },
            {
              "name": "expr-imperative.ts",
              "path": "src/lib/cad/expr-imperative.ts",
              "loc": 353
            },
            {
              "name": "expr-list.test.ts",
              "path": "src/lib/cad/expr-list.test.ts",
              "loc": 239
            },
            {
              "name": "expr-loops.test.ts",
              "path": "src/lib/cad/expr-loops.test.ts",
              "loc": 62
            },
            {
              "name": "expr-loops.ts",
              "path": "src/lib/cad/expr-loops.ts",
              "loc": 105
            },
            {
              "name": "expr-multiline.test.ts",
              "path": "src/lib/cad/expr-multiline.test.ts",
              "loc": 65
            },
            {
              "name": "expr-node.test.ts",
              "path": "src/lib/cad/expr-node.test.ts",
              "loc": 142
            },
            {
              "name": "expr-schema.ts",
              "path": "src/lib/cad/expr-schema.ts",
              "loc": 140
            },
            {
              "name": "expr-validate.test.ts",
              "path": "src/lib/cad/expr-validate.test.ts",
              "loc": 115
            },
            {
              "name": "graph-exprs.test.ts",
              "path": "src/lib/cad/graph-exprs.test.ts",
              "loc": 168
            },
            {
              "name": "graph-exprs.ts",
              "path": "src/lib/cad/graph-exprs.ts",
              "loc": 689
            },
            {
              "name": "graph-to-tf.test.ts",
              "path": "src/lib/cad/graph-to-tf.test.ts",
              "loc": 397
            },
            {
              "name": "graph-to-tf.ts",
              "path": "src/lib/cad/graph-to-tf.ts",
              "loc": 943
            },
            {
              "name": "manifold-helpers-meta.ts",
              "path": "src/lib/cad/manifold-helpers-meta.ts",
              "loc": 162
            },
            {
              "name": "manifold-helpers.ts",
              "path": "src/lib/cad/manifold-helpers.ts",
              "loc": 588
            },
            {
              "name": "manifold-mesh.ts",
              "path": "src/lib/cad/manifold-mesh.ts",
              "loc": 962
            },
            {
              "name": "math-lib.ts",
              "path": "src/lib/cad/math-lib.ts",
              "loc": 51
            },
            {
              "name": "mesh-serial.test.ts",
              "path": "src/lib/cad/mesh-serial.test.ts",
              "loc": 42
            },
            {
              "name": "mesh-serial.ts",
              "path": "src/lib/cad/mesh-serial.ts",
              "loc": 122
            },
            {
              "name": "param-keys.ts",
              "path": "src/lib/cad/param-keys.ts",
              "loc": 101
            },
            {
              "name": "part-id.ts",
              "path": "src/lib/cad/part-id.ts",
              "loc": 71
            },
            {
              "name": "port-suggest.test.ts",
              "path": "src/lib/cad/port-suggest.test.ts",
              "loc": 99
            },
            {
              "name": "port-suggest.ts",
              "path": "src/lib/cad/port-suggest.ts",
              "loc": 203
            },
            {
              "name": "port-types.test.ts",
              "path": "src/lib/cad/port-types.test.ts",
              "loc": 125
            },
            {
              "name": "port-types.ts",
              "path": "src/lib/cad/port-types.ts",
              "loc": 226
            },
            {
              "name": "primitive-sandbox.ts",
              "path": "src/lib/cad/primitive-sandbox.ts",
              "loc": 63
            },
            {
              "name": "primitive-stub.test.ts",
              "path": "src/lib/cad/primitive-stub.test.ts",
              "loc": 96
            },
            {
              "name": "primitive-stub.ts",
              "path": "src/lib/cad/primitive-stub.ts",
              "loc": 232
            },
            {
              "name": "profile-templates.ts",
              "path": "src/lib/cad/profile-templates.ts",
              "loc": 489
            },
            {
              "name": "render-helpers.ts",
              "path": "src/lib/cad/render-helpers.ts",
              "loc": 979
            },
            {
              "name": "revolve-axial.test.ts",
              "path": "src/lib/cad/revolve-axial.test.ts",
              "loc": 120
            },
            {
              "name": "sketch-collayout.test.ts",
              "path": "src/lib/cad/sketch-collayout.test.ts",
              "loc": 117
            },
            {
              "name": "sketch-layout.ts",
              "path": "src/lib/cad/sketch-layout.ts",
              "loc": 109
            },
            {
              "name": "sketch-repeat.test.ts",
              "path": "src/lib/cad/sketch-repeat.test.ts",
              "loc": 224
            },
            {
              "name": "sketch-repeat.ts",
              "path": "src/lib/cad/sketch-repeat.ts",
              "loc": 125
            },
            {
              "name": "sketch.test.ts",
              "path": "src/lib/cad/sketch.test.ts",
              "loc": 330
            },
            {
              "name": "sketch.ts",
              "path": "src/lib/cad/sketch.ts",
              "loc": 280
            },
            {
              "name": "spline-eval.test.ts",
              "path": "src/lib/cad/spline-eval.test.ts",
              "loc": 87
            },
            {
              "name": "spline-eval.ts",
              "path": "src/lib/cad/spline-eval.ts",
              "loc": 87
            },
            {
              "name": "spline-resample.test.ts",
              "path": "src/lib/cad/spline-resample.test.ts",
              "loc": 162
            },
            {
              "name": "spline-resample.ts",
              "path": "src/lib/cad/spline-resample.ts",
              "loc": 173
            },
            {
              "name": "stack.test.ts",
              "path": "src/lib/cad/stack.test.ts",
              "loc": 297
            },
            {
              "name": "struct-type.test.ts",
              "path": "src/lib/cad/struct-type.test.ts",
              "loc": 198
            },
            {
              "name": "struct-type.ts",
              "path": "src/lib/cad/struct-type.ts",
              "loc": 418
            },
            {
              "name": "subdivide-axial.test.ts",
              "path": "src/lib/cad/subdivide-axial.test.ts",
              "loc": 163
            },
            {
              "name": "sweep-cap-triangulation.test.ts",
              "path": "src/lib/cad/sweep-cap-triangulation.test.ts",
              "loc": 178
            },
            {
              "name": "sweep-rmf.test.ts",
              "path": "src/lib/cad/sweep-rmf.test.ts",
              "loc": 112
            },
            {
              "name": "sweep-self-intersection.test.ts",
              "path": "src/lib/cad/sweep-self-intersection.test.ts",
              "loc": 76
            },
            {
              "name": "tf-wat-emit.test.ts",
              "path": "src/lib/cad/tf-wat-emit.test.ts",
              "loc": 132
            },
            {
              "name": "tf-wat-emit.ts",
              "path": "src/lib/cad/tf-wat-emit.ts",
              "loc": 166
            },
            {
              "name": "warp-geom.test.ts",
              "path": "src/lib/cad/warp-geom.test.ts",
              "loc": 48
            },
            {
              "name": "warp-geom.ts",
              "path": "src/lib/cad/warp-geom.ts",
              "loc": 39
            },
            {
              "name": "warp-mesh-js.test.ts",
              "path": "src/lib/cad/warp-mesh-js.test.ts",
              "loc": 35
            },
            {
              "name": "warp-node.test.ts",
              "path": "src/lib/cad/warp-node.test.ts",
              "loc": 111
            },
            {
              "name": "warp-spline.test.ts",
              "path": "src/lib/cad/warp-spline.test.ts",
              "loc": 136
            },
            {
              "name": "warp-spline.ts",
              "path": "src/lib/cad/warp-spline.ts",
              "loc": 626
            },
            {
              "name": "wire-check.test.ts",
              "path": "src/lib/cad/wire-check.test.ts",
              "loc": 102
            },
            {
              "name": "wire-check.ts",
              "path": "src/lib/cad/wire-check.ts",
              "loc": 110
            }
          ]
        },
        {
          "name": "server",
          "path": "src/lib/server",
          "children": [
            {
              "name": "__brep_sweep_spike.test.ts",
              "path": "src/lib/server/__brep_sweep_spike.test.ts",
              "loc": 162
            },
            {
              "name": "bake-cache.test.ts",
              "path": "src/lib/server/bake-cache.test.ts",
              "loc": 102
            },
            {
              "name": "bake-cache.ts",
              "path": "src/lib/server/bake-cache.ts",
              "loc": 280
            },
            {
              "name": "brep-occt.ts",
              "path": "src/lib/server/brep-occt.ts",
              "loc": 607
            },
            {
              "name": "dep-inherit.test.ts",
              "path": "src/lib/server/dep-inherit.test.ts",
              "loc": 41
            },
            {
              "name": "manifold-bake.ts",
              "path": "src/lib/server/manifold-bake.ts",
              "loc": 541
            },
            {
              "name": "part-colors.test.ts",
              "path": "src/lib/server/part-colors.test.ts",
              "loc": 84
            },
            {
              "name": "part-colors.ts",
              "path": "src/lib/server/part-colors.ts",
              "loc": 309
            },
            {
              "name": "primitive-loader.ts",
              "path": "src/lib/server/primitive-loader.ts",
              "loc": 926
            },
            {
              "name": "primitive-paths.test.ts",
              "path": "src/lib/server/primitive-paths.test.ts",
              "loc": 70
            },
            {
              "name": "primitive-paths.ts",
              "path": "src/lib/server/primitive-paths.ts",
              "loc": 205
            },
            {
              "name": "primitives-meta.ts",
              "path": "src/lib/server/primitives-meta.ts",
              "loc": 190
            },
            {
              "name": "profile-fn.ts",
              "path": "src/lib/server/profile-fn.ts",
              "loc": 118
            },
            {
              "name": "rag-corpus.ts",
              "path": "src/lib/server/rag-corpus.ts",
              "loc": 283
            },
            {
              "name": "rag-l1.ts",
              "path": "src/lib/server/rag-l1.ts",
              "loc": 187
            },
            {
              "name": "rag-prompt.ts",
              "path": "src/lib/server/rag-prompt.ts",
              "loc": 216
            },
            {
              "name": "rag-query.ts",
              "path": "src/lib/server/rag-query.ts",
              "loc": 174
            },
            {
              "name": "recognize-composite.ts",
              "path": "src/lib/server/recognize-composite.ts",
              "loc": 482
            },
            {
              "name": "script-cache.ts",
              "path": "src/lib/server/script-cache.ts",
              "loc": 120
            },
            {
              "name": "script-compile.test.ts",
              "path": "src/lib/server/script-compile.test.ts",
              "loc": 183
            },
            {
              "name": "stdlib.ts",
              "path": "src/lib/server/stdlib.ts",
              "loc": 121
            },
            {
              "name": "volume.ts",
              "path": "src/lib/server/volume.ts",
              "loc": 175
            }
          ]
        },
        {
          "name": "shared",
          "path": "src/lib/shared",
          "children": [
            {
              "name": "graph-editor",
              "path": "src/lib/shared/graph-editor",
              "children": [
                {
                  "name": "expr",
                  "path": "src/lib/shared/graph-editor/expr",
                  "children": [
                    {
                      "name": "ExprCodeEditor.svelte",
                      "path": "src/lib/shared/graph-editor/expr/ExprCodeEditor.svelte",
                      "loc": 132
                    },
                    {
                      "name": "ExpressionBuilderPopup.svelte",
                      "path": "src/lib/shared/graph-editor/expr/ExpressionBuilderPopup.svelte",
                      "loc": 523
                    },
                    {
                      "name": "ExpressionsMenu.svelte",
                      "path": "src/lib/shared/graph-editor/expr/ExpressionsMenu.svelte",
                      "loc": 264
                    },
                    {
                      "name": "ExpressionSrcPane.svelte",
                      "path": "src/lib/shared/graph-editor/expr/ExpressionSrcPane.svelte",
                      "loc": 196
                    },
                    {
                      "name": "ExprImperativeBlocks.svelte",
                      "path": "src/lib/shared/graph-editor/expr/ExprImperativeBlocks.svelte",
                      "loc": 486
                    }
                  ]
                },
                {
                  "name": "AiMenu.svelte",
                  "path": "src/lib/shared/graph-editor/AiMenu.svelte",
                  "loc": 298
                },
                {
                  "name": "args.ts",
                  "path": "src/lib/shared/graph-editor/args.ts",
                  "loc": 80
                },
                {
                  "name": "AutoWireSuggestPanel.svelte",
                  "path": "src/lib/shared/graph-editor/AutoWireSuggestPanel.svelte",
                  "loc": 121
                },
                {
                  "name": "BakeMenu.svelte",
                  "path": "src/lib/shared/graph-editor/BakeMenu.svelte",
                  "loc": 106
                },
                {
                  "name": "canvas-interaction.svelte.ts",
                  "path": "src/lib/shared/graph-editor/canvas-interaction.svelte.ts",
                  "loc": 97
                },
                {
                  "name": "CanvasMenu.svelte",
                  "path": "src/lib/shared/graph-editor/CanvasMenu.svelte",
                  "loc": 119
                },
                {
                  "name": "delete-confirm.svelte.ts",
                  "path": "src/lib/shared/graph-editor/delete-confirm.svelte.ts",
                  "loc": 78
                },
                {
                  "name": "ge-assist.svelte.ts",
                  "path": "src/lib/shared/graph-editor/ge-assist.svelte.ts",
                  "loc": 187
                },
                {
                  "name": "ge-assist.test.ts",
                  "path": "src/lib/shared/graph-editor/ge-assist.test.ts",
                  "loc": 197
                },
                {
                  "name": "ge-assist.ts",
                  "path": "src/lib/shared/graph-editor/ge-assist.ts",
                  "loc": 235
                },
                {
                  "name": "geom.test.ts",
                  "path": "src/lib/shared/graph-editor/geom.test.ts",
                  "loc": 224
                },
                {
                  "name": "geom.ts",
                  "path": "src/lib/shared/graph-editor/geom.ts",
                  "loc": 531
                },
                {
                  "name": "graph-editor-bake.svelte.ts",
                  "path": "src/lib/shared/graph-editor/graph-editor-bake.svelte.ts",
                  "loc": 128
                },
                {
                  "name": "graph-editor-bake.test.ts",
                  "path": "src/lib/shared/graph-editor/graph-editor-bake.test.ts",
                  "loc": 80
                },
                {
                  "name": "graph-editor-bake.ts",
                  "path": "src/lib/shared/graph-editor/graph-editor-bake.ts",
                  "loc": 51
                },
                {
                  "name": "graph-history.svelte.ts",
                  "path": "src/lib/shared/graph-editor/graph-history.svelte.ts",
                  "loc": 78
                },
                {
                  "name": "graph-layout-actions.ts",
                  "path": "src/lib/shared/graph-editor/graph-layout-actions.ts",
                  "loc": 175
                },
                {
                  "name": "GraphEditorPane.svelte",
                  "path": "src/lib/shared/graph-editor/GraphEditorPane.svelte",
                  "loc": 4381
                },
                {
                  "name": "MaterialEditorPopover.svelte",
                  "path": "src/lib/shared/graph-editor/MaterialEditorPopover.svelte",
                  "loc": 112
                },
                {
                  "name": "node-palette.test.ts",
                  "path": "src/lib/shared/graph-editor/node-palette.test.ts",
                  "loc": 64
                },
                {
                  "name": "node-palette.ts",
                  "path": "src/lib/shared/graph-editor/node-palette.ts",
                  "loc": 116
                },
                {
                  "name": "NodeCard.svelte",
                  "path": "src/lib/shared/graph-editor/NodeCard.svelte",
                  "loc": 2454
                },
                {
                  "name": "ParamsCard.svelte",
                  "path": "src/lib/shared/graph-editor/ParamsCard.svelte",
                  "loc": 169
                },
                {
                  "name": "pointer-capture.ts",
                  "path": "src/lib/shared/graph-editor/pointer-capture.ts",
                  "loc": 20
                },
                {
                  "name": "poly-preview-state.svelte.ts",
                  "path": "src/lib/shared/graph-editor/poly-preview-state.svelte.ts",
                  "loc": 383
                },
                {
                  "name": "PolyPreview.svelte",
                  "path": "src/lib/shared/graph-editor/PolyPreview.svelte",
                  "loc": 443
                },
                {
                  "name": "popover-clamp.test.ts",
                  "path": "src/lib/shared/graph-editor/popover-clamp.test.ts",
                  "loc": 37
                },
                {
                  "name": "popover-clamp.ts",
                  "path": "src/lib/shared/graph-editor/popover-clamp.ts",
                  "loc": 66
                },
                {
                  "name": "Popovers.svelte",
                  "path": "src/lib/shared/graph-editor/Popovers.svelte",
                  "loc": 570
                },
                {
                  "name": "profile-preview-state.svelte.ts",
                  "path": "src/lib/shared/graph-editor/profile-preview-state.svelte.ts",
                  "loc": 200
                },
                {
                  "name": "ProfilePreview.svelte",
                  "path": "src/lib/shared/graph-editor/ProfilePreview.svelte",
                  "loc": 167
                },
                {
                  "name": "PropertiesCard.svelte",
                  "path": "src/lib/shared/graph-editor/PropertiesCard.svelte",
                  "loc": 178
                },
                {
                  "name": "RepeatEditorPane.svelte",
                  "path": "src/lib/shared/graph-editor/RepeatEditorPane.svelte",
                  "loc": 299
                },
                {
                  "name": "RightPane.svelte",
                  "path": "src/lib/shared/graph-editor/RightPane.svelte",
                  "loc": 786
                },
                {
                  "name": "sketch-state.svelte.ts",
                  "path": "src/lib/shared/graph-editor/sketch-state.svelte.ts",
                  "loc": 774
                },
                {
                  "name": "SketchEditorPane.svelte",
                  "path": "src/lib/shared/graph-editor/SketchEditorPane.svelte",
                  "loc": 646
                },
                {
                  "name": "SketchNodeCard.svelte",
                  "path": "src/lib/shared/graph-editor/SketchNodeCard.svelte",
                  "loc": 269
                },
                {
                  "name": "spline-state.svelte.ts",
                  "path": "src/lib/shared/graph-editor/spline-state.svelte.ts",
                  "loc": 150
                },
                {
                  "name": "SplineEditorPopup.svelte",
                  "path": "src/lib/shared/graph-editor/SplineEditorPopup.svelte",
                  "loc": 254
                },
                {
                  "name": "SplineScene.svelte",
                  "path": "src/lib/shared/graph-editor/SplineScene.svelte",
                  "loc": 283
                },
                {
                  "name": "tf-recipe-timing.test.ts",
                  "path": "src/lib/shared/graph-editor/tf-recipe-timing.test.ts",
                  "loc": 70
                },
                {
                  "name": "tf-recipe-timing.ts",
                  "path": "src/lib/shared/graph-editor/tf-recipe-timing.ts",
                  "loc": 53
                },
                {
                  "name": "wire-state.svelte.ts",
                  "path": "src/lib/shared/graph-editor/wire-state.svelte.ts",
                  "loc": 445
                },
                {
                  "name": "WireLayer.svelte",
                  "path": "src/lib/shared/graph-editor/WireLayer.svelte",
                  "loc": 552
                }
              ]
            },
            {
              "name": "tf_examples",
              "path": "src/lib/shared/tf_examples",
              "children": [
                {
                  "name": "bored_pipe.ts",
                  "path": "src/lib/shared/tf_examples/bored_pipe.ts",
                  "loc": 27
                },
                {
                  "name": "box.ts",
                  "path": "src/lib/shared/tf_examples/box.ts",
                  "loc": 20
                },
                {
                  "name": "cone.ts",
                  "path": "src/lib/shared/tf_examples/cone.ts",
                  "loc": 33
                },
                {
                  "name": "dp_joint.test.ts",
                  "path": "src/lib/shared/tf_examples/dp_joint.test.ts",
                  "loc": 89
                },
                {
                  "name": "dp_joint.ts",
                  "path": "src/lib/shared/tf_examples/dp_joint.ts",
                  "loc": 114
                },
                {
                  "name": "dp_pin.ts",
                  "path": "src/lib/shared/tf_examples/dp_pin.ts",
                  "loc": 43
                },
                {
                  "name": "dp_stand.test.ts",
                  "path": "src/lib/shared/tf_examples/dp_stand.test.ts",
                  "loc": 121
                },
                {
                  "name": "dp_stand.ts",
                  "path": "src/lib/shared/tf_examples/dp_stand.ts",
                  "loc": 103
                },
                {
                  "name": "excluded.ts",
                  "path": "src/lib/shared/tf_examples/excluded.ts",
                  "loc": 29
                },
                {
                  "name": "execute.test.ts",
                  "path": "src/lib/shared/tf_examples/execute.test.ts",
                  "loc": 475
                },
                {
                  "name": "execute.ts",
                  "path": "src/lib/shared/tf_examples/execute.ts",
                  "loc": 466
                },
                {
                  "name": "extrude.test.ts",
                  "path": "src/lib/shared/tf_examples/extrude.test.ts",
                  "loc": 330
                },
                {
                  "name": "extrude.ts",
                  "path": "src/lib/shared/tf_examples/extrude.ts",
                  "loc": 155
                },
                {
                  "name": "helix.ts",
                  "path": "src/lib/shared/tf_examples/helix.ts",
                  "loc": 33
                },
                {
                  "name": "index.test.ts",
                  "path": "src/lib/shared/tf_examples/index.test.ts",
                  "loc": 56
                },
                {
                  "name": "index.ts",
                  "path": "src/lib/shared/tf_examples/index.ts",
                  "loc": 84
                },
                {
                  "name": "mandrel.test.ts",
                  "path": "src/lib/shared/tf_examples/mandrel.test.ts",
                  "loc": 94
                },
                {
                  "name": "mandrel.ts",
                  "path": "src/lib/shared/tf_examples/mandrel.ts",
                  "loc": 57
                },
                {
                  "name": "mule_shoe.test.ts",
                  "path": "src/lib/shared/tf_examples/mule_shoe.test.ts",
                  "loc": 58
                },
                {
                  "name": "mule_shoe.ts",
                  "path": "src/lib/shared/tf_examples/mule_shoe.ts",
                  "loc": 71
                },
                {
                  "name": "nipple_f.test.ts",
                  "path": "src/lib/shared/tf_examples/nipple_f.test.ts",
                  "loc": 88
                },
                {
                  "name": "nipple_f.ts",
                  "path": "src/lib/shared/tf_examples/nipple_f.ts",
                  "loc": 69
                },
                {
                  "name": "r_cyl.ts",
                  "path": "src/lib/shared/tf_examples/r_cyl.ts",
                  "loc": 21
                },
                {
                  "name": "revolve.test.ts",
                  "path": "src/lib/shared/tf_examples/revolve.test.ts",
                  "loc": 93
                },
                {
                  "name": "revolve.ts",
                  "path": "src/lib/shared/tf_examples/revolve.ts",
                  "loc": 114
                },
                {
                  "name": "s_cyl.ts",
                  "path": "src/lib/shared/tf_examples/s_cyl.ts",
                  "loc": 29
                },
                {
                  "name": "s_tub_st.test.ts",
                  "path": "src/lib/shared/tf_examples/s_tub_st.test.ts",
                  "loc": 50
                },
                {
                  "name": "s_tub_st.ts",
                  "path": "src/lib/shared/tf_examples/s_tub_st.ts",
                  "loc": 106
                },
                {
                  "name": "s_tube_demo.test.ts",
                  "path": "src/lib/shared/tf_examples/s_tube_demo.test.ts",
                  "loc": 56
                },
                {
                  "name": "s_tube_demo.ts",
                  "path": "src/lib/shared/tf_examples/s_tube_demo.ts",
                  "loc": 113
                },
                {
                  "name": "s_tube_no_ext.ts",
                  "path": "src/lib/shared/tf_examples/s_tube_no_ext.ts",
                  "loc": 60
                },
                {
                  "name": "tf-weld.test.ts",
                  "path": "src/lib/shared/tf_examples/tf-weld.test.ts",
                  "loc": 157
                },
                {
                  "name": "tf-weld.ts",
                  "path": "src/lib/shared/tf_examples/tf-weld.ts",
                  "loc": 172
                },
                {
                  "name": "warp-densify.test.ts",
                  "path": "src/lib/shared/tf_examples/warp-densify.test.ts",
                  "loc": 151
                },
                {
                  "name": "warp-pipeline.test.ts",
                  "path": "src/lib/shared/tf_examples/warp-pipeline.test.ts",
                  "loc": 132
                },
                {
                  "name": "weld_extrude_demo.ts",
                  "path": "src/lib/shared/tf_examples/weld_extrude_demo.ts",
                  "loc": 62
                }
              ]
            },
            {
              "name": "_shaft_bisect.test.ts",
              "path": "src/lib/shared/_shaft_bisect.test.ts",
              "loc": 144
            },
            {
              "name": "anthropic-api.ts",
              "path": "src/lib/shared/anthropic-api.ts",
              "loc": 20
            },
            {
              "name": "brep-adapter.test.ts",
              "path": "src/lib/shared/brep-adapter.test.ts",
              "loc": 60
            },
            {
              "name": "brep-adapter.ts",
              "path": "src/lib/shared/brep-adapter.ts",
              "loc": 61
            },
            {
              "name": "CacheBrowser.svelte",
              "path": "src/lib/shared/CacheBrowser.svelte",
              "loc": 444
            },
            {
              "name": "CompJsonSilhouette.svelte",
              "path": "src/lib/shared/CompJsonSilhouette.svelte",
              "loc": 198
            },
            {
              "name": "dragNumber.ts",
              "path": "src/lib/shared/dragNumber.ts",
              "loc": 81
            },
            {
              "name": "floating-tip.ts",
              "path": "src/lib/shared/floating-tip.ts",
              "loc": 92
            },
            {
              "name": "FolderTreeSidebar.svelte",
              "path": "src/lib/shared/FolderTreeSidebar.svelte",
              "loc": 365
            },
            {
              "name": "instance-colors.ts",
              "path": "src/lib/shared/instance-colors.ts",
              "loc": 72
            },
            {
              "name": "material-preset.test.ts",
              "path": "src/lib/shared/material-preset.test.ts",
              "loc": 34
            },
            {
              "name": "material-preset.ts",
              "path": "src/lib/shared/material-preset.ts",
              "loc": 64
            },
            {
              "name": "material-textures.test.ts",
              "path": "src/lib/shared/material-textures.test.ts",
              "loc": 64
            },
            {
              "name": "material-textures.ts",
              "path": "src/lib/shared/material-textures.ts",
              "loc": 180
            },
            {
              "name": "NavMenu.svelte",
              "path": "src/lib/shared/NavMenu.svelte",
              "loc": 132
            },
            {
              "name": "ParamGrid.svelte",
              "path": "src/lib/shared/ParamGrid.svelte",
              "loc": 210
            },
            {
              "name": "PrimitiveDualCanvas.svelte",
              "path": "src/lib/shared/PrimitiveDualCanvas.svelte",
              "loc": 1057
            },
            {
              "name": "PrimitiveDualScene.svelte",
              "path": "src/lib/shared/PrimitiveDualScene.svelte",
              "loc": 1097
            },
            {
              "name": "PrimitiveSvgView.svelte",
              "path": "src/lib/shared/PrimitiveSvgView.svelte",
              "loc": 587
            },
            {
              "name": "profile-fn-compose.test.ts",
              "path": "src/lib/shared/profile-fn-compose.test.ts",
              "loc": 133
            },
            {
              "name": "profile-fn-compose.ts",
              "path": "src/lib/shared/profile-fn-compose.ts",
              "loc": 294
            },
            {
              "name": "profile-presets.test.ts",
              "path": "src/lib/shared/profile-presets.test.ts",
              "loc": 73
            },
            {
              "name": "profile-presets.ts",
              "path": "src/lib/shared/profile-presets.ts",
              "loc": 391
            },
            {
              "name": "ProfileFn3DCanvas.svelte",
              "path": "src/lib/shared/ProfileFn3DCanvas.svelte",
              "loc": 95
            },
            {
              "name": "ProfileFnEditor.svelte",
              "path": "src/lib/shared/ProfileFnEditor.svelte",
              "loc": 926
            },
            {
              "name": "ProfilePalette.svelte",
              "path": "src/lib/shared/ProfilePalette.svelte",
              "loc": 201
            },
            {
              "name": "scene-state.svelte.ts",
              "path": "src/lib/shared/scene-state.svelte.ts",
              "loc": 191
            },
            {
              "name": "SceneControls.svelte",
              "path": "src/lib/shared/SceneControls.svelte",
              "loc": 235
            },
            {
              "name": "svg-camera.ts",
              "path": "src/lib/shared/svg-camera.ts",
              "loc": 103
            },
            {
              "name": "svg-emit.ts",
              "path": "src/lib/shared/svg-emit.ts",
              "loc": 469
            },
            {
              "name": "svg-reduce.test.ts",
              "path": "src/lib/shared/svg-reduce.test.ts",
              "loc": 83
            },
            {
              "name": "svg-reduce.ts",
              "path": "src/lib/shared/svg-reduce.ts",
              "loc": 131
            },
            {
              "name": "tf-bake-client.ts",
              "path": "src/lib/shared/tf-bake-client.ts",
              "loc": 199
            },
            {
              "name": "tf-worker-core.test.ts",
              "path": "src/lib/shared/tf-worker-core.test.ts",
              "loc": 135
            },
            {
              "name": "tf-worker-core.ts",
              "path": "src/lib/shared/tf-worker-core.ts",
              "loc": 141
            },
            {
              "name": "tf-worker.ts",
              "path": "src/lib/shared/tf-worker.ts",
              "loc": 56
            },
            {
              "name": "trueform-adapter.test.ts",
              "path": "src/lib/shared/trueform-adapter.test.ts",
              "loc": 292
            },
            {
              "name": "trueform-adapter.ts",
              "path": "src/lib/shared/trueform-adapter.ts",
              "loc": 384
            },
            {
              "name": "trueform-client.test.ts",
              "path": "src/lib/shared/trueform-client.test.ts",
              "loc": 253
            },
            {
              "name": "trueform-client.ts",
              "path": "src/lib/shared/trueform-client.ts",
              "loc": 559
            },
            {
              "name": "TypeDefinerPanel.svelte",
              "path": "src/lib/shared/TypeDefinerPanel.svelte",
              "loc": 253
            },
            {
              "name": "TypeDefinerPopover.svelte",
              "path": "src/lib/shared/TypeDefinerPopover.svelte",
              "loc": 66
            },
            {
              "name": "vertex-alpha-partition.test.ts",
              "path": "src/lib/shared/vertex-alpha-partition.test.ts",
              "loc": 82
            },
            {
              "name": "vertex-alpha-partition.ts",
              "path": "src/lib/shared/vertex-alpha-partition.ts",
              "loc": 89
            },
            {
              "name": "warp.ts",
              "path": "src/lib/shared/warp.ts",
              "loc": 195
            },
            {
              "name": "WellSideNav.svelte",
              "path": "src/lib/shared/WellSideNav.svelte",
              "loc": 477
            }
          ]
        },
        {
          "name": "test-stubs",
          "path": "src/lib/test-stubs",
          "children": [
            {
              "name": "env-dynamic-private.ts",
              "path": "src/lib/test-stubs/env-dynamic-private.ts",
              "loc": 6
            }
          ]
        },
        {
          "name": "wells",
          "path": "src/lib/wells",
          "children": [
            {
              "name": "threeD",
              "path": "src/lib/wells/threeD",
              "children": [
                {
                  "name": "parametric",
                  "path": "src/lib/wells/threeD/parametric",
                  "children": [
                    {
                      "name": "bakerPacker.ts",
                      "path": "src/lib/wells/threeD/parametric/bakerPacker.ts",
                      "loc": 98
                    },
                    {
                      "name": "index.ts",
                      "path": "src/lib/wells/threeD/parametric/index.ts",
                      "loc": 99
                    },
                    {
                      "name": "ParametricComponent.ts",
                      "path": "src/lib/wells/threeD/parametric/ParametricComponent.ts",
                      "loc": 90
                    }
                  ]
                },
                {
                  "name": "direction.ts",
                  "path": "src/lib/wells/threeD/direction.ts",
                  "loc": 212
                },
                {
                  "name": "index.ts",
                  "path": "src/lib/wells/threeD/index.ts",
                  "loc": 68
                },
                {
                  "name": "manifoldCut.ts",
                  "path": "src/lib/wells/threeD/manifoldCut.ts",
                  "loc": 510
                },
                {
                  "name": "profile.ts",
                  "path": "src/lib/wells/threeD/profile.ts",
                  "loc": 140
                }
              ]
            },
            {
              "name": "assemble.test.ts",
              "path": "src/lib/wells/assemble.test.ts",
              "loc": 73
            },
            {
              "name": "assemble.ts",
              "path": "src/lib/wells/assemble.ts",
              "loc": 128
            },
            {
              "name": "dtx.ts",
              "path": "src/lib/wells/dtx.ts",
              "loc": 95
            },
            {
              "name": "registry.ts",
              "path": "src/lib/wells/registry.ts",
              "loc": 81
            },
            {
              "name": "samples.ts",
              "path": "src/lib/wells/samples.ts",
              "loc": 29
            },
            {
              "name": "schematic3d.test.ts",
              "path": "src/lib/wells/schematic3d.test.ts",
              "loc": 340
            },
            {
              "name": "WellScene.svelte",
              "path": "src/lib/wells/WellScene.svelte",
              "loc": 83
            },
            {
              "name": "WellSchematic3D.svelte",
              "path": "src/lib/wells/WellSchematic3D.svelte",
              "loc": 532
            },
            {
              "name": "wson-2d.test.ts",
              "path": "src/lib/wells/wson-2d.test.ts",
              "loc": 207
            },
            {
              "name": "wson-2d.ts",
              "path": "src/lib/wells/wson-2d.ts",
              "loc": 507
            },
            {
              "name": "wson-mutate.test.ts",
              "path": "src/lib/wells/wson-mutate.test.ts",
              "loc": 73
            },
            {
              "name": "wson-mutate.ts",
              "path": "src/lib/wells/wson-mutate.ts",
              "loc": 57
            },
            {
              "name": "wson.test.ts",
              "path": "src/lib/wells/wson.test.ts",
              "loc": 54
            },
            {
              "name": "wson.ts",
              "path": "src/lib/wells/wson.ts",
              "loc": 160
            }
          ]
        },
        {
          "name": "rate_limit.ts",
          "path": "src/lib/rate_limit.ts",
          "loc": 26
        }
      ]
    },
    {
      "name": "routes",
      "path": "src/routes",
      "children": [
        {
          "name": "api",
          "path": "src/routes/api",
          "children": [
            {
              "name": "__dev_restart",
              "path": "src/routes/api/__dev_restart",
              "children": [
                {
                  "name": "+server.ts",
                  "path": "src/routes/api/__dev_restart/+server.ts",
                  "loc": 53
                }
              ]
            },
            {
              "name": "brep",
              "path": "src/routes/api/brep",
              "children": [
                {
                  "name": "preview",
                  "path": "src/routes/api/brep/preview",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/brep/preview/+server.ts",
                      "loc": 63
                    }
                  ]
                }
              ]
            },
            {
              "name": "cache",
              "path": "src/routes/api/cache",
              "children": [
                {
                  "name": "bake-stats",
                  "path": "src/routes/api/cache/bake-stats",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/cache/bake-stats/+server.ts",
                      "loc": 92
                    }
                  ]
                },
                {
                  "name": "clear",
                  "path": "src/routes/api/cache/clear",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/cache/clear/+server.ts",
                      "loc": 23
                    }
                  ]
                },
                {
                  "name": "delete",
                  "path": "src/routes/api/cache/delete",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/cache/delete/+server.ts",
                      "loc": 117
                    }
                  ]
                },
                {
                  "name": "entry",
                  "path": "src/routes/api/cache/entry",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/cache/entry/+server.ts",
                      "loc": 65
                    }
                  ]
                },
                {
                  "name": "list",
                  "path": "src/routes/api/cache/list",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/cache/list/+server.ts",
                      "loc": 95
                    }
                  ]
                },
                {
                  "name": "stats",
                  "path": "src/routes/api/cache/stats",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/cache/stats/+server.ts",
                      "loc": 25
                    }
                  ]
                }
              ]
            },
            {
              "name": "manifest",
              "path": "src/routes/api/manifest",
              "children": [
                {
                  "name": "+server.ts",
                  "path": "src/routes/api/manifest/+server.ts",
                  "loc": 72
                }
              ]
            },
            {
              "name": "primitives",
              "path": "src/routes/api/primitives",
              "children": [
                {
                  "name": "bake-preview",
                  "path": "src/routes/api/primitives/bake-preview",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/bake-preview/+server.ts",
                      "loc": 116
                    }
                  ]
                },
                {
                  "name": "compile",
                  "path": "src/routes/api/primitives/compile",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/compile/+server.ts",
                      "loc": 90
                    }
                  ]
                },
                {
                  "name": "delete",
                  "path": "src/routes/api/primitives/delete",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/delete/+server.ts",
                      "loc": 65
                    }
                  ]
                },
                {
                  "name": "describe",
                  "path": "src/routes/api/primitives/describe",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/describe/+server.ts",
                      "loc": 75
                    }
                  ]
                },
                {
                  "name": "folder",
                  "path": "src/routes/api/primitives/folder",
                  "children": [
                    {
                      "name": "delete",
                      "path": "src/routes/api/primitives/folder/delete",
                      "children": [
                        {
                          "name": "+server.ts",
                          "path": "src/routes/api/primitives/folder/delete/+server.ts",
                          "loc": 57
                        }
                      ]
                    },
                    {
                      "name": "move",
                      "path": "src/routes/api/primitives/folder/move",
                      "children": [
                        {
                          "name": "+server.ts",
                          "path": "src/routes/api/primitives/folder/move/+server.ts",
                          "loc": 50
                        }
                      ]
                    },
                    {
                      "name": "rename",
                      "path": "src/routes/api/primitives/folder/rename",
                      "children": [
                        {
                          "name": "+server.ts",
                          "path": "src/routes/api/primitives/folder/rename/+server.ts",
                          "loc": 39
                        }
                      ]
                    }
                  ]
                },
                {
                  "name": "instructions",
                  "path": "src/routes/api/primitives/instructions",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/instructions/+server.ts",
                      "loc": 60
                    }
                  ]
                },
                {
                  "name": "list",
                  "path": "src/routes/api/primitives/list",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/list/+server.ts",
                      "loc": 202
                    }
                  ]
                },
                {
                  "name": "mkdir",
                  "path": "src/routes/api/primitives/mkdir",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/mkdir/+server.ts",
                      "loc": 32
                    }
                  ]
                },
                {
                  "name": "move",
                  "path": "src/routes/api/primitives/move",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/move/+server.ts",
                      "loc": 73
                    }
                  ]
                },
                {
                  "name": "preview",
                  "path": "src/routes/api/primitives/preview",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/preview/+server.ts",
                      "loc": 379
                    }
                  ]
                },
                {
                  "name": "profiles",
                  "path": "src/routes/api/primitives/profiles",
                  "children": [
                    {
                      "name": "delete",
                      "path": "src/routes/api/primitives/profiles/delete",
                      "children": [
                        {
                          "name": "+server.ts",
                          "path": "src/routes/api/primitives/profiles/delete/+server.ts",
                          "loc": 21
                        }
                      ]
                    },
                    {
                      "name": "list",
                      "path": "src/routes/api/primitives/profiles/list",
                      "children": [
                        {
                          "name": "+server.ts",
                          "path": "src/routes/api/primitives/profiles/list/+server.ts",
                          "loc": 66
                        }
                      ]
                    },
                    {
                      "name": "resolve",
                      "path": "src/routes/api/primitives/profiles/resolve",
                      "children": [
                        {
                          "name": "+server.ts",
                          "path": "src/routes/api/primitives/profiles/resolve/+server.ts",
                          "loc": 46
                        }
                      ]
                    },
                    {
                      "name": "save",
                      "path": "src/routes/api/primitives/profiles/save",
                      "children": [
                        {
                          "name": "+server.ts",
                          "path": "src/routes/api/primitives/profiles/save/+server.ts",
                          "loc": 76
                        }
                      ]
                    },
                    {
                      "name": "source",
                      "path": "src/routes/api/primitives/profiles/source",
                      "children": [
                        {
                          "name": "+server.ts",
                          "path": "src/routes/api/primitives/profiles/source/+server.ts",
                          "loc": 50
                        }
                      ]
                    }
                  ]
                },
                {
                  "name": "prompts",
                  "path": "src/routes/api/primitives/prompts",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/prompts/+server.ts",
                      "loc": 98
                    }
                  ]
                },
                {
                  "name": "recognize",
                  "path": "src/routes/api/primitives/recognize",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/recognize/+server.ts",
                      "loc": 21
                    }
                  ]
                },
                {
                  "name": "refine",
                  "path": "src/routes/api/primitives/refine",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/refine/+server.ts",
                      "loc": 299
                    }
                  ]
                },
                {
                  "name": "rename",
                  "path": "src/routes/api/primitives/rename",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/rename/+server.ts",
                      "loc": 123
                    }
                  ]
                },
                {
                  "name": "restore",
                  "path": "src/routes/api/primitives/restore",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/restore/+server.ts",
                      "loc": 48
                    }
                  ]
                },
                {
                  "name": "save",
                  "path": "src/routes/api/primitives/save",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/save/+server.ts",
                      "loc": 97
                    }
                  ]
                },
                {
                  "name": "source",
                  "path": "src/routes/api/primitives/source",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/source/+server.ts",
                      "loc": 101
                    }
                  ]
                },
                {
                  "name": "types",
                  "path": "src/routes/api/primitives/types",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/primitives/types/+server.ts",
                      "loc": 65
                    }
                  ]
                }
              ]
            },
            {
              "name": "rag",
              "path": "src/routes/api/rag",
              "children": [
                {
                  "name": "assist",
                  "path": "src/routes/api/rag/assist",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/rag/assist/+server.ts",
                      "loc": 158
                    }
                  ]
                },
                {
                  "name": "prompt",
                  "path": "src/routes/api/rag/prompt",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/rag/prompt/+server.ts",
                      "loc": 92
                    }
                  ]
                },
                {
                  "name": "rebuild",
                  "path": "src/routes/api/rag/rebuild",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/rag/rebuild/+server.ts",
                      "loc": 24
                    }
                  ]
                },
                {
                  "name": "scan-refs",
                  "path": "src/routes/api/rag/scan-refs",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/rag/scan-refs/+server.ts",
                      "loc": 186
                    }
                  ]
                },
                {
                  "name": "stats",
                  "path": "src/routes/api/rag/stats",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/rag/stats/+server.ts",
                      "loc": 17
                    }
                  ]
                }
              ]
            },
            {
              "name": "tf",
              "path": "src/routes/api/tf",
              "children": [
                {
                  "name": "compile",
                  "path": "src/routes/api/tf/compile",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/tf/compile/+server.ts",
                      "loc": 153
                    }
                  ]
                },
                {
                  "name": "compile-wasm",
                  "path": "src/routes/api/tf/compile-wasm",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/tf/compile-wasm/+server.ts",
                      "loc": 64
                    }
                  ]
                }
              ]
            },
            {
              "name": "vocab",
              "path": "src/routes/api/vocab",
              "children": [
                {
                  "name": "bake-proposed",
                  "path": "src/routes/api/vocab/bake-proposed",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/vocab/bake-proposed/+server.ts",
                      "loc": 89
                    }
                  ]
                },
                {
                  "name": "infer",
                  "path": "src/routes/api/vocab/infer",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/vocab/infer/+server.ts",
                      "loc": 120
                    }
                  ]
                },
                {
                  "name": "promote",
                  "path": "src/routes/api/vocab/promote",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/vocab/promote/+server.ts",
                      "loc": 107
                    }
                  ]
                },
                {
                  "name": "promote-proposed",
                  "path": "src/routes/api/vocab/promote-proposed",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/vocab/promote-proposed/+server.ts",
                      "loc": 126
                    }
                  ]
                },
                {
                  "name": "regenerate",
                  "path": "src/routes/api/vocab/regenerate",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/vocab/regenerate/+server.ts",
                      "loc": 161
                    }
                  ]
                }
              ]
            },
            {
              "name": "volume",
              "path": "src/routes/api/volume",
              "children": [
                {
                  "name": "backup",
                  "path": "src/routes/api/volume/backup",
                  "children": [
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/volume/backup/+server.ts",
                      "loc": 110
                    }
                  ]
                },
                {
                  "name": "onedrive",
                  "path": "src/routes/api/volume/onedrive",
                  "children": [
                    {
                      "name": "diff",
                      "path": "src/routes/api/volume/onedrive/diff",
                      "children": [
                        {
                          "name": "+server.ts",
                          "path": "src/routes/api/volume/onedrive/diff/+server.ts",
                          "loc": 126
                        }
                      ]
                    },
                    {
                      "name": "sync-paths",
                      "path": "src/routes/api/volume/onedrive/sync-paths",
                      "children": [
                        {
                          "name": "+server.ts",
                          "path": "src/routes/api/volume/onedrive/sync-paths/+server.ts",
                          "loc": 180
                        }
                      ]
                    },
                    {
                      "name": "+server.ts",
                      "path": "src/routes/api/volume/onedrive/+server.ts",
                      "loc": 53
                    }
                  ]
                },
                {
                  "name": "+server.ts",
                  "path": "src/routes/api/volume/+server.ts",
                  "loc": 217
                }
              ]
            }
          ]
        },
        {
          "name": "design",
          "path": "src/routes/design",
          "children": [
            {
              "name": "nodes",
              "path": "src/routes/design/nodes",
              "children": [
                {
                  "name": "ArchNode.svelte",
                  "path": "src/routes/design/nodes/ArchNode.svelte",
                  "loc": 135
                },
                {
                  "name": "ContainerNode.svelte",
                  "path": "src/routes/design/nodes/ContainerNode.svelte",
                  "loc": 148
                }
              ]
            },
            {
              "name": "+page.svelte",
              "path": "src/routes/design/+page.svelte",
              "loc": 709
            },
            {
              "name": "ArchGraph.svelte",
              "path": "src/routes/design/ArchGraph.svelte",
              "loc": 425
            },
            {
              "name": "architecture.ts",
              "path": "src/routes/design/architecture.ts",
              "loc": 760
            },
            {
              "name": "c4.ts",
              "path": "src/routes/design/c4.ts",
              "loc": 313
            },
            {
              "name": "C4View.svelte",
              "path": "src/routes/design/C4View.svelte",
              "loc": 483
            },
            {
              "name": "domain-classes.ts",
              "path": "src/routes/design/domain-classes.ts",
              "loc": 102
            },
            {
              "name": "folder-hierarchy.ts",
              "path": "src/routes/design/folder-hierarchy.ts",
              "loc": 94
            },
            {
              "name": "folder-tree.ts",
              "path": "src/routes/design/folder-tree.ts",
              "loc": 2658
            },
            {
              "name": "FolderArc.svelte",
              "path": "src/routes/design/FolderArc.svelte",
              "loc": 196
            },
            {
              "name": "FolderCirclePack.svelte",
              "path": "src/routes/design/FolderCirclePack.svelte",
              "loc": 169
            },
            {
              "name": "FolderEdgeBundle.svelte",
              "path": "src/routes/design/FolderEdgeBundle.svelte",
              "loc": 183
            },
            {
              "name": "FolderHierarchy.svelte",
              "path": "src/routes/design/FolderHierarchy.svelte",
              "loc": 211
            },
            {
              "name": "FolderIcicle.svelte",
              "path": "src/routes/design/FolderIcicle.svelte",
              "loc": 177
            },
            {
              "name": "FolderTree.svelte",
              "path": "src/routes/design/FolderTree.svelte",
              "loc": 172
            },
            {
              "name": "FolderTreemap.svelte",
              "path": "src/routes/design/FolderTreemap.svelte",
              "loc": 135
            },
            {
              "name": "gep-modules.ts",
              "path": "src/routes/design/gep-modules.ts",
              "loc": 196
            },
            {
              "name": "GepModuleGraph.svelte",
              "path": "src/routes/design/GepModuleGraph.svelte",
              "loc": 319
            },
            {
              "name": "UmlClassDiagram.svelte",
              "path": "src/routes/design/UmlClassDiagram.svelte",
              "loc": 160
            }
          ]
        },
        {
          "name": "graph-editor",
          "path": "src/routes/graph-editor",
          "children": [
            {
              "name": "+page.svelte",
              "path": "src/routes/graph-editor/+page.svelte",
              "loc": 32
            }
          ]
        },
        {
          "name": "plan",
          "path": "src/routes/plan",
          "children": [
            {
              "name": "+page.svelte",
              "path": "src/routes/plan/+page.svelte",
              "loc": 728
            },
            {
              "name": "details.ts",
              "path": "src/routes/plan/details.ts",
              "loc": 220
            }
          ]
        },
        {
          "name": "primitives",
          "path": "src/routes/primitives",
          "children": [
            {
              "name": "profiles",
              "path": "src/routes/primitives/profiles",
              "children": [
                {
                  "name": "+page.svelte",
                  "path": "src/routes/primitives/profiles/+page.svelte",
                  "loc": 187
                }
              ]
            },
            {
              "name": "types",
              "path": "src/routes/primitives/types",
              "children": [
                {
                  "name": "+page.svelte",
                  "path": "src/routes/primitives/types/+page.svelte",
                  "loc": 31
                }
              ]
            },
            {
              "name": "+page.svelte",
              "path": "src/routes/primitives/+page.svelte",
              "loc": 2298
            },
            {
              "name": "primitives-tree.test.ts",
              "path": "src/routes/primitives/primitives-tree.test.ts",
              "loc": 139
            },
            {
              "name": "primitives-tree.ts",
              "path": "src/routes/primitives/primitives-tree.ts",
              "loc": 191
            }
          ]
        },
        {
          "name": "research",
          "path": "src/routes/research",
          "children": [
            {
              "name": "[slug]",
              "path": "src/routes/research/[slug]",
              "children": [
                {
                  "name": "+page.svelte",
                  "path": "src/routes/research/[slug]/+page.svelte",
                  "loc": 137
                }
              ]
            },
            {
              "name": "+page.svelte",
              "path": "src/routes/research/+page.svelte",
              "loc": 140
            },
            {
              "name": "docs.ts",
              "path": "src/routes/research/docs.ts",
              "loc": 122
            }
          ]
        },
        {
          "name": "vocab",
          "path": "src/routes/vocab",
          "children": [
            {
              "name": "_tabs",
              "path": "src/routes/vocab/_tabs",
              "children": [
                {
                  "name": "BrowsePane.svelte",
                  "path": "src/routes/vocab/_tabs/BrowsePane.svelte",
                  "loc": 105
                },
                {
                  "name": "CuratedDetail.svelte",
                  "path": "src/routes/vocab/_tabs/CuratedDetail.svelte",
                  "loc": 169
                },
                {
                  "name": "InferredTab.svelte",
                  "path": "src/routes/vocab/_tabs/InferredTab.svelte",
                  "loc": 216
                },
                {
                  "name": "ProposedTab.svelte",
                  "path": "src/routes/vocab/_tabs/ProposedTab.svelte",
                  "loc": 272
                }
              ]
            },
            {
              "name": "+page.server.ts",
              "path": "src/routes/vocab/+page.server.ts",
              "loc": 38
            },
            {
              "name": "+page.svelte",
              "path": "src/routes/vocab/+page.svelte",
              "loc": 1006
            }
          ]
        },
        {
          "name": "volume",
          "path": "src/routes/volume",
          "children": [
            {
              "name": "+page.svelte",
              "path": "src/routes/volume/+page.svelte",
              "loc": 912
            }
          ]
        },
        {
          "name": "wells",
          "path": "src/routes/wells",
          "children": [
            {
              "name": "+page.svelte",
              "path": "src/routes/wells/+page.svelte",
              "loc": 806
            },
            {
              "name": "label-layout.test.ts",
              "path": "src/routes/wells/label-layout.test.ts",
              "loc": 91
            },
            {
              "name": "label-layout.ts",
              "path": "src/routes/wells/label-layout.ts",
              "loc": 118
            },
            {
              "name": "view-settings.ts",
              "path": "src/routes/wells/view-settings.ts",
              "loc": 71
            },
            {
              "name": "WellCompPopup.svelte",
              "path": "src/routes/wells/WellCompPopup.svelte",
              "loc": 189
            },
            {
              "name": "WellDepthRuler.svelte",
              "path": "src/routes/wells/WellDepthRuler.svelte",
              "loc": 157
            },
            {
              "name": "WellElementRail.svelte",
              "path": "src/routes/wells/WellElementRail.svelte",
              "loc": 158
            },
            {
              "name": "WellPopover.svelte",
              "path": "src/routes/wells/WellPopover.svelte",
              "loc": 124
            },
            {
              "name": "WellSchematic2D.svelte",
              "path": "src/routes/wells/WellSchematic2D.svelte",
              "loc": 302
            },
            {
              "name": "WellTimingBadge.svelte",
              "path": "src/routes/wells/WellTimingBadge.svelte",
              "loc": 76
            },
            {
              "name": "WellToolbar.svelte",
              "path": "src/routes/wells/WellToolbar.svelte",
              "loc": 141
            },
            {
              "name": "WellViewControls.svelte",
              "path": "src/routes/wells/WellViewControls.svelte",
              "loc": 253
            },
            {
              "name": "WellViewPlaceholder.svelte",
              "path": "src/routes/wells/WellViewPlaceholder.svelte",
              "loc": 213
            },
            {
              "name": "workspace-cache.test.ts",
              "path": "src/routes/wells/workspace-cache.test.ts",
              "loc": 87
            },
            {
              "name": "workspace-cache.ts",
              "path": "src/routes/wells/workspace-cache.ts",
              "loc": 256
            },
            {
              "name": "wson-summary.ts",
              "path": "src/routes/wells/wson-summary.ts",
              "loc": 154
            }
          ]
        },
        {
          "name": "+layout.svelte",
          "path": "src/routes/+layout.svelte",
          "loc": 41
        },
        {
          "name": "+layout.ts",
          "path": "src/routes/+layout.ts",
          "loc": 3
        },
        {
          "name": "+page.svelte",
          "path": "src/routes/+page.svelte",
          "loc": 426
        }
      ]
    },
    {
      "name": "app.css",
      "path": "src/app.css",
      "loc": 50
    },
    {
      "name": "app.html",
      "path": "src/app.html",
      "loc": 13
    },
    {
      "name": "hooks.server.ts",
      "path": "src/hooks.server.ts",
      "loc": 256
    }
  ]
};
