/**
 * POST /api/author/suggest
 *
 * Claude-assisted authoring hints. Takes the current AuthoredComponent
 * spec + a free-text prompt from the user, retrieves similar authored
 * components as few-shot context, and asks Claude to suggest concrete
 * editing steps (add/modify/remove parts or ops).
 *
 * Mirrors the prompt structure of /api/identify — catalog is
 * cache_control: ephemeral so repeated calls within the 5-min TTL share
 * a prompt-cache prefix.
 */

import { json, error } from '@sveltejs/kit';
import Anthropic from '@anthropic-ai/sdk';
import { COMPONENTS } from '$lib/components/library';
import { env } from '$env/dynamic/private';
import { getAuthoredCache } from '$lib/authoring/cache';
import type { AuthoredComponent } from '$lib/authoring/schema';
import type { RequestHandler } from './$types';
import { join } from 'path';
import { readFileSync, existsSync } from 'fs';

const CACHE_PATH = join(process.cwd(), 'training_data', 'authored_cache.jsonl');
const CONTEXT_PATH = join(process.cwd(), 'training_data', 'authored_context.md');
const TOP_K = 3;

export const POST: RequestHandler = async ({ request }) => {
  if (!env.ANTHROPIC_API_KEY) {
    throw error(500, 'ANTHROPIC_API_KEY not set');
  }

  let body: { spec: AuthoredComponent; prompt: string };
  try {
    body = await request.json();
  } catch {
    throw error(400, 'Invalid JSON body');
  }

  if (!body.spec || !body.prompt?.trim()) {
    throw error(400, 'Request must include spec (AuthoredComponent) and prompt (string)');
  }

  // === 1. Build the primitive catalog (cached across calls) ===
  const catalog = COMPONENTS.map((c) => {
    const params = Object.entries(c.params)
      .map(([k, p]) => `${k}: ${p.min}-${p.max} ${p.unit ?? ''}`.trim())
      .join(', ');
    return `- ${c.id}: ${c.name} — ${c.description} | Params: ${params}`;
  }).join('\n');

  // === 2. Retrieve similar prior authored components ===
  const cache = await getAuthoredCache(CACHE_PATH);
  const similar = cache.findSimilar(body.spec.hash ?? null, TOP_K);

  // === 3. Build the prompt ===
  const content: any[] = [];

  // Catalog block — ephemeral so it's prompt-cached for 5 min
  content.push({
    type: 'text',
    text: `You are a CAD component authoring assistant. The user is building a composed component from these primitives:

PRIMITIVE CATALOG (${COMPONENTS.length} types):
${catalog}

COMPOSITION RULES:
- Each "part" references a primitive by id and supplies params + an optional transform ({tx,ty,tz,rx,ry,rz}).
- Parts are combined via CSG "ops": union, subtract, intersect. Each op takes 2+ input ids and produces an output id.
- Z is the axial direction (Z-down convention). Parts stack along Z by shifting tz.
- When adding a part, always provide a unique id (e.g. "p2"), valid primitive id, reasonable params within the catalog ranges, and a transform that positions it relative to existing parts.

OUTPUT FORMAT:
Return ONLY a JSON object:
{
  "suggestions": [
    {
      "action": "add_part" | "modify_part" | "remove_part" | "add_op" | "modify_op" | "remove_op",
      "part": { "id": "...", "prim": "...", "params": {...}, "transform": {...} },
      "op": { "op": "union"|"subtract"|"intersect", "inputs": [...], "out": "..." },
      "target_id": "...",
      "changes": { ... },
      "reasoning": "brief explanation"
    }
  ]
}

Include only the fields relevant to each action:
- add_part: include "part"
- modify_part: include "target_id" + "changes" (partial part fields to merge)
- remove_part: include "target_id"
- add_op / modify_op / remove_op: include "op" or "target_id" as appropriate`,
    cache_control: { type: 'ephemeral' },
  });

  // Growing context doc — global summary of all authored components.
  // Loaded lazily from disk (regenerated by /api/author/save).
  if (existsSync(CONTEXT_PATH)) {
    try {
      const contextDoc = readFileSync(CONTEXT_PATH, 'utf-8');
      if (contextDoc.trim()) {
        content.push({
          type: 'text',
          text: `\n\nAUTHORED COMPONENT LIBRARY:\n${contextDoc}`,
        });
      }
    } catch { /* non-fatal — proceed without context */ }
  }

  // Few-shot: prior authored components (if any exist)
  if (similar.length > 0) {
    content.push({
      type: 'text',
      text: `\n\nHere are ${similar.length} previously authored components for reference:\n` +
        similar.map((r, i) => {
          const partSummary = r.parts.map(p => `${p.id}:${p.prim}`).join(', ');
          const opSummary = r.ops.length > 0
            ? r.ops.map(o => `${o.out}=${o.op}(${o.inputs.join(',')})`).join(', ')
            : 'none';
          return `Example ${i + 1}: "${r.name}" — ${r.description || 'no description'}\n  Parts: ${partSummary}\n  Ops: ${opSummary}`;
        }).join('\n'),
    });
  }

  // Current spec + user prompt
  const specSummary = {
    name: body.spec.name || '(untitled)',
    parts: body.spec.parts,
    ops: body.spec.ops,
  };

  content.push({
    type: 'text',
    text: `\n\nCURRENT COMPONENT SPEC:\n${JSON.stringify(specSummary, null, 2)}

USER REQUEST: ${body.prompt.trim()}`,
  });

  // === 4. Call Claude ===
  const client = new Anthropic({ apiKey: env.ANTHROPIC_API_KEY });

  try {
    console.log(`[author/suggest] prompt="${body.prompt.trim().slice(0, 80)}", parts=${body.spec.parts.length}, prior=${similar.length}`);

    const response = await client.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 2048,
      messages: [{ role: 'user', content }],
    });

    let text = (response.content[0] as any).text.trim();
    if (text.includes('```')) {
      text = text.split('```')[1];
      if (text.startsWith('json')) text = text.slice(4);
      text = text.trim();
    }

    const result = JSON.parse(text);
    return json(result);
  } catch (e: any) {
    console.error('[author/suggest] error:', e);
    throw error(500, e.message || 'Suggest failed');
  }
};
